### PR TITLE
[SH] Fix warnings about unhandled switch cases by adding defaults.

### PR DESCRIPTION
**Pull request by Rot127**
https://github.com/capstone-engine/capstone/issues/2010#issuecomment-1545909273

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
A few still left:
```
 arch/SH/SHDisassembler.c: In function ‘op4xxb’:
arch/SH/SHDisassembler.c:960:33: warning: ‘rw’ may be used uninitialized [-Wmaybe-uninitialized]
  960 |                                 set_reg_n(info, SH_REG_R0, rw, rw, detail);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c: In function ‘op4xx5’:
arch/SH/SHDisassembler.c:24:9: warning: ‘rw’ may be used uninitialized [-Wmaybe-uninitialized]
   24 |         switch(rw) {
      |         ^~~~~~
arch/SH/SHDisassembler.c:752:24: note: ‘rw’ was declared here
  752 |         enum direction rw;
      |                        ^~
```
https://github.com/capstone-engine/capstone/actions/runs/4962032517/jobs/8879573977?pr=2017#step:5:55

**Comment by Rot127** [comment]
Thanks. `cmake` and clangd did not catch this for whatever reason. Even with `-Wmaybe-uninitialized` added to compile options.

**Review by XVilka — APPROVED** [review]
All clear now.

**Comment by trufae** [comment]
Can we merge this so I can start testing from the next branch? Thanks @Rot127 ^_^

**Comment by XVilka** [comment]
@kabeor @aquynh

**Comment by kabeor** [comment]
Thanks, merged.

**Pull request merged**
