### PR TITLE
Expose displacementOffset and immediateOffset;Corrected x86 immediate sizes

### PR DESCRIPTION
**Pull request by bughoho**
https://github.com/aquynh/capstone/issues/509

### CODE REVIEW

**Comment by aquynh** [comment]
since these new fields in cs_x86 are all for encoding purpose, would you mind putting all of them into a a structure named **encode**?

@oleavr, @stevemk14ebr, @hlide, @mtivadar, @progopis, @obs1dium, @kokole : this is the feature you requested. any comments?

thanks.

**Comment by stevemk14ebr** [comment]
Put them in a struct like you mentioned and also adding a flag to see if the value is relevant as @kokole suggested. Other than that i think this is adequate for now.

**Comment by bughoho** [comment]
Oops,I think i found a bug in the next version.

012D1126  |.  A3 0C202D01          mov     dword ptr ds:[0x12D200C],eax

InternalInstruction::displacement == 0
InternalInstruction::displacementOffset == 0
InternalInstruction::displacementSize == 0

because readDisplacement has not been executed.
this bug occur in readOperands function
https://github.com/aquynh/capstone/blob/master/arch/X86/X86DisassemblerDecoder.c#L2059

**Comment by obs1dium** [comment]
@bughoho I modified and extended your code and created a PR for it. Can also create a PR for the official repo instead if needed.

**Comment by aquynh** [comment]
yes, you can either open a PR here, or let @bughoho merge your PR, then i can pull from it.

thanks.

**Comment by bughoho** [comment]
great!

**Comment by oleavr** [comment]
Awesome work! :heart: This will make it a lot easier to keep track of the latest Capstone in Frida. :tada:

**Comment by aquynh** [comment]
i pulled and pushed this work to a new branch "encoding" at https://github.com/aquynh/capstone/tree/encoding. to keep it simple, please do PR for this branch. thanks.

**Comment by aquynh** [comment]
@oleavr, @stevemk14ebr, @hlide, @mtivadar, @progopis, @kokole: can you please try the branch "encoding" to see if it does what you requested? all the related encoding offsets/sizes are in cs_x86_encoding struct at https://github.com/aquynh/capstone/blob/encoding/include/capstone/x86.h#L263

**Comment by obs1dium** [comment]
Found and fixed two more issues (#539), other than that everything's working fine so far.

**Comment by aquynh** [comment]
this is already handled in https://github.com/aquynh/capstone/tree/encoding. will review to merge this branch into "next" soon, thanks.

**Comment by obs1dium** [comment]
Would be great if the encoding branch could be merged soon, I'm heavily relying on this information.

**Comment by stevemk14ebr** [comment]
I second this, I use it heavily too

**Comment by aquynh** [comment]
can anybody fix the Python binding for this? Python binding currently breaks due to this, and that is why i havent merged it to "next" branch yet.

**Comment by obs1dium** [comment]
I'm not super familiar with Python, but managed to build the bindings from the master branch with this branch, which seemed to work fine expect that the Python code does not have access to the new fields yet. Maybe I'm missing something?

**Comment by stevemk14ebr** [comment]
Ping? Sorry i can't tribute atm, working on my own project for now (that uses this encoding branch heavily)

**Comment by stevemk14ebr** [comment]
@aquynh if i did the work to merge port the commits related to the encoding feature branch here to 'next' would it be merged? Offset of immediate and offset of displacement specifically.

**Comment by aquynh** [comment]
Yes, but please update the Python binding at the same time, then do pull
req. Thanks!

**Comment by aquynh** [comment]
i guess you can cherry-pick something from https://github.com/baumane/capstone, which seems to update for Python binding.

**Comment by stevemk14ebr** [comment]
close this and delete encoding branch now that we have https://github.com/aquynh/capstone/pull/1187 ?

**Comment by aquynh** [comment]
@obs1dium, most part of your original pull req is now in "next" branch. looks like what is missing now is just the encoding size (based on https://github.com/aquynh/capstone/commit/f2a66cd5247ccf31271d3f4c62b84b124d60a8ee ?). could you please send a pull req for that now?

**Comment by stevemk14ebr** [comment]
it's in master i think you mean, i'll port to next in my free time once we hear back from what @obs1dium wants to do

**Comment by obs1dium** [comment]
I'll have to compare the current master branch against my own version, looks like the immediate size encoding information isn't fully merged yet, like you said.

**Comment by obs1dium** [comment]
Looks like you merged #1187 into master, though?

**Comment by aquynh** [comment]
That was a mistake, it must be ported to the next branch. I will revert
that in master.

**Comment by stevemk14ebr** [comment]
You can compare against my master on my fork, then I can do the work to Port to next in a week or two when I get some time

**Comment by stevemk14ebr** [comment]
If you have the encoding features already imemented in next could you do a pr? That would be faster and easier than me porting to next manually

**Comment by obs1dium** [comment]
@stevemk14ebr I created a PR for the next branch in your repository, hopefully I didn't miss anything. You'll still have to merge the changes you made to the Python bindings.

**Comment by stevemk14ebr** [comment]
@obs1dium awesome ill merge the bindings and do some basic testing. Can you explain why disp was widened to 64 bits? I never understood that while i was picking

`int64_t                       displacement`

**Comment by obs1dium** [comment]
I think that was a fix to support mov rax, moffs64, c.f. https://github.com/aquynh/capstone/commit/2d5b0a3308489896d5b08595e67db92a675a4f71

**Comment by stevemk14ebr** [comment]
thanks for your work @obs1dium your merge passed all my tests without any changes. Just had to add bindings

**Comment by aquynh** [comment]
```
I think that was a fix to support mov rax, moffs64, c.f. 2d5b0a3
```

@obs1dium, can you provide a sample input for this case?

**Comment by obs1dium** [comment]
Try disassembling `0x48, 0xa1, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88` in 64-bit mode. The second operand is a memory operand with a disp vaue of `0x8877665544332211`.

**Comment by aquynh** [comment]
yes that is the right fix

**Comment by obs1dium** [comment]
@aquynh Looks like a small bug got into my earlier merge, I'll send you a PR

**Comment by stevemk14ebr** [comment]
is this PR and the encoding branch no longer needed now that the PR to next was merged? Delete them?

**Comment by aquynh** [comment]
right, i deleted the encoding branch.

**Comment by aquynh** [comment]
@obs1dium, do you mean this bug was introduced by you? but that line was added by me back in 2014.

how did you find this issue?

**Comment by obs1dium** [comment]
The bug triggered an assertion in my code. It wasn't there in the encoding branch, must have been introduced in the merge.

**Comment by aquynh** [comment]
Can you give an input affected by this?

**Comment by obs1dium** [comment]
Any opcode with a memory operand that doesn't use a displacement, e.g. `lea rax,[rdx + r9*2]`
`insn->consumedDisplacement` musn't be set to true in that case (`insn->eaDisplacement == EA_DISP_NONE`)

**Comment by XVilka** [comment]
@radare do you think this might be useful for r2?

**Comment by radare** [comment]
woah, a 4 yo PR with tons of conflicts, not sure if that matters in next :?

**Comment by aquynh** [comment]
this was merged into v4/next branches long ago. thanks.

**Pull request closed without merging**
