### PR TITLE
ppc: fix registers overflow (next)

### PR DESCRIPTION
**Pull request by StalkR**
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236

Same as https://github.com/aquynh/capstone/pull/1687 for next branch

### CODE REVIEW

**Comment by catenacyber** [comment]
@StalkR for some context information, this bug comes from llvm cf https://reviews.llvm.org/D61935

The good way to fix it would be to sync with latest LLVM cf #1510

**Comment by StalkR** [comment]
OK good to know, up to @aquynh then.

When will #1510 be merged?

If not soon, this is a small patch just for the overflow the fuzzers are hitting (`Regs[RegNo]` with `RegNo` beyond `Regs`) that could be used in the meantime.

**Comment by catenacyber** [comment]
> If not soon, this is a small patch just for the overflow the fuzzers are hitting (Regs[RegNo] with RegNo beyond Regs) that could be used in the meantime.

Sounds good.

@aquynh I guess you will not update PPC soon, so this workaround seems fair.

**Comment by StalkR** [comment]
friendly ping @aquynh

**Comment by pranith** [comment]
Can you please create a new PR on [libcapstone](https://github.com/libcapstone/libcapstone)?

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
