### PR TITLE
x86: update read/write registers for transfer instructions

### PR DESCRIPTION
**Pull request by hainest**
This is mostly a self-serving update to simplify migrating https://github.com/dyninst/dyninst to Capstone. I the move to Zydis (https://github.com/capstone-engine/capstone/discussions/2505), but I need these updates sooner than that is likely to happen.

There are still missing implicit memory writes to the stack pointer for most of these instructions (e.g., `ret` pops the stack), but I won't add them here since that's more involved than just updating the instruction tables. Zydis does have that information.

### CODE REVIEW

**Comment by Rot127** [comment]
Some tests of `project/tests/details/x86.yaml` failed.
You can use the Python `cstest` or the `cstest` tool written in C.

**Comment by Rot127** [comment]
Just saw that I haven't fixed the build instructions for cstest yet.
Please see https://github.com/capstone-engine/capstone/pull/2580 how to use it.

Essentially you can build `cstest` if you are on Linux (requires a `libyaml-dev` package installed and `-DCAPSTONE_BUILD_CSTEST`). Or you can use the `cstest_py` Python `cstest`.

Install with:

```
pip install bindings/python/
pip install bindings/python/cstest_py
```

**Comment by hainest** [comment]
Tests are now passing. I needed to update the expected results for `call` instructions (they now all write the IP).

```console
$ ctest --test-dir build --output-on-failure
Internal ctest changing into directory: /capstone-engine/capstone/build
Test project /capstone-engine/capstone/build
      Start  1: MCTests
 1/13 Test  #1: MCTests ..........................   Passed    1.62 sec
      Start  2: DetailTests
 2/13 Test  #2: DetailTests ......................   Passed    0.02 sec
      Start  3: IssueTests
 3/13 Test  #3: IssueTests .......................   Passed    0.01 sec
      Start  4: FeaturesTests
 4/13 Test  #4: FeaturesTests ....................   Passed    0.00 sec
      Start  5: unit_cstest
 5/13 Test  #5: unit_cstest ......................   Passed    0.00 sec
      Start  6: integration_cstest
 6/13 Test  #6: integration_cstest ...............   Passed    0.04 sec
      Start  7: legacy_test_skipdata
 7/13 Test  #7: legacy_test_skipdata .............   Passed    0.00 sec
      Start  8: legacy_test_iter
 8/13 Test  #8: legacy_test_iter .................   Passed    0.00 sec
      Start  9: legacy_test_customized_mnem
 9/13 Test  #9: legacy_test_customized_mnem ......   Passed    0.00 sec
      Start 10: integration_compat_headers
10/13 Test #10: integration_compat_headers .......   Passed    0.00 sec
      Start 11: integration_test_litbase
11/13 Test #11: integration_test_litbase .........   Passed    0.00 sec
      Start 12: unit_sstream
12/13 Test #12: unit_sstream .....................   Passed    0.00 sec
      Start 13: unit_utils
13/13 Test #13: unit_utils .......................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 13
```

**Review by Rot127 — APPROVED** [review]

**Comment by XVilka** [comment]
@kabeor

**Review by kabeor — APPROVED** [review]
Thank you for your contribution.

**Pull request merged**
