### PR TITLE
fix #686

### LINKED ISSUE #686: document: docs/README should probably refer to contrib/cs_driver for Windows driver
This is open discussion.

docs/README currently refers to KernelProject for a sample on using Capstone from a Windows driver. 
> * Sample application on how to embed Capstone into Windows kernel driver.
> 
> 	https://github.com/aquynh/KernelProject

This project is, however, not too easy to use as a reference due to insufficient documents, a use of a two years old revision of Capstone, and unnecessarily large number of accompanying library files.   

Instead, the README could refer to a cs_driver sample project included in the Capstone repository.
- https://github.com/aquynh/capstone/tree/master/contrib/cs_driver

This project comes with a single one file with sufficient code and comments on how to use Capstone from a Windows kernel driver, and moreover, is supported and maintained as a part of Capstone repo.

This discussion should probably involve with @zer0mem, the original author of the KernelProject project, since he may have another idea to address the above downsides.

### PR DESCRIPTION
**Pull request by tandasat**
Updates docs/README as discussed on #686.

I am hoping to hear @zer0mem's thoughts , but have not heard back since I personally talked to him a week ago.

### CODE REVIEW

**Comment by aquynh** [comment]
how about instead of removing the link to @zer0mem project, you add a note to say it can be a good  example for implementing Windows driver from scratch, but be warned it can have this issue & that issue etc?

**Comment by tandasat** [comment]
Yeah, I bit hesitate to take off his pioneer work from the doc. 

But I personally do not believe that the KernelProject is no longer the easiest way to learn how to use Capstone from a driver, and prefer to keep the README and descriptions to be as concise as possible. So how do you think about this? 
```
* Sample applications on how to embed Capstone into Windows kernel driver.

	https://github.com/aquynh/capstone/tree/master/contrib/cs_driver (in C, basic)
	https://github.com/aquynh/KernelProject (in C++)
```

If you rather prefer to have descriptive notes like you suggested, I am open to write it also.

**Comment by aquynh** [comment]
yes this looks good to me, please update the PR

**Comment by tandasat** [comment]
I updated the PR. Let me know if you have any concerns.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
