### PR TITLE
MSVC tooling updates

### PR DESCRIPTION
**Pull request by hmoenck**
Resolved some issues when building with MSVC:
- PlatformToolset always defaulted to Visual Studio 10 (v100), regardless of used version. I made the property sheet to fix this optional, so it is less intrusive to other developers.
- Some implicit casts caused warnings
- test_basic does not exist (?) but was referenced in the solution

### CODE REVIEW

**Comment by pranith** [comment]
Can you please create a new PR on [libcapstone](https://github.com/libcapstone/libcapstone)?

**Comment by tmfink** [comment]
@pranith instead of asking folks to make duplicate pull requests to your fork, you can wait until the changes are merged into this repo. Once the pull requests get merged, you can just merge/cherry-pick the changes into your fork.

That is half the work for the submitters and generates fewer notifications for those who follow development of this repo. :smiley:

**Comment by pranith** [comment]
@tmfink The reason I ask is because there are PRs that are more than 6 months old. It might be better to continue development on the fork. But I heard back from @aquynh today. Let's see how it turns out.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
