### PR TITLE
Small arm64 compat header fixes

### PR DESCRIPTION
**Pull request by satk0**
**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

First of all, thanks a lot for making those changes to arm64 compat header :) 

I've tried to use the newest csnext in r2 and found some things missing so I've made this PR implementing it, hope it helps :sweat_smile:

### CODE REVIEW

**Comment by Rot127** [comment]
Thanks! Please also fix it in the header generator script and add these two to the test `c` file.

**Comment by satk0** [comment]
Allright, thanks for such a quick response

**Comment by satk0** [comment]
Is that it? I couldn't find this test c file you were talking about to add it here ;/

**Review by Rot127 — APPROVED** [review]
All good. Thanks a lot!

**Comment by XVilka** [comment]
@kabeor please merge this one

**Review by kabeor — APPROVED** [review]
Thank you!

**Comment by Rot127** [comment]
@satk0 Can you rebase please?

For whatever reason Github doesn't want to merge this one.

**Comment by satk0** [comment]
Allright, give me 5 minutes

**Comment by satk0** [comment]
@Rot127 Done

**Pull request merged**
