### PR TITLE
Correct register access attributes of ARM's umlal and umaal

### PR DESCRIPTION
**Pull request by covanam**
These instructions **accumulate**, so they do read the destination registers.

### CODE REVIEW

**Comment by Rot127** [comment]
Thanks for the PR! We are just in the process of finishing up a really big ARM update which is based on LLVM 16 (https://github.com/capstone-engine/capstone/pull/1949). I checked the instructions and they are handled there correctly.

Could you please provide me the bytes of instructions which test this. Just to make sure everything works.

**Comment by covanam** [comment]
> Thanks for the PR! We are just in the process of finishing up a really big ARM update which is based on LLVM 16 (#1949). I checked the instructions and they are handled there correctly.
> 
> Could you please provide me the bytes of instructions which test this. Just to make sure everything works.

Sure! Here are the instructions that broke for me:

    AA FB 0C 20    umull r2, r0, sl, ip
    EA FB 0C 20    umlal r2, r0, sl, ip
    EA FB 0C 7C    umlal r7, ip, sl, ip

Expect read/write attributes are: `RW, RW, R, R` for all 3 instructions.
As before, encoding is Thumb little endian.

Thanks!

**Comment by Rot127** [comment]
I get `W, W, R, R` for the `umull` instruction. Which seems to be correct according to the manual (https://developer.arm.com/documentation/ddi0406/cb/Application-Level-Architecture/Instruction-Details/Alphabetical-list-of-instructions/UMULL?lang=en).

```
./cstool -d thumb  AAFB0C20EAFB0C20EAFB0C7C
 0  aa fb 0c 20  umull	r2, r0, r10, r12
	ID: 501 (vabal)
	op_count: 4
		operands[0].type: REG = r2
		operands[0].access: WRITE
		operands[1].type: REG = r0
		operands[1].access: WRITE
		operands[2].type: REG = r10
		operands[2].access: READ
		operands[3].type: REG = r12
		operands[3].access: READ
	Registers read: r10 r12
	Registers modified: r2 r0
	Groups: IsThumb2 

 4  ea fb 0c 20  umlal	r2, r0, r10, r12
	ID: 500 (uxth)
	op_count: 4
		operands[0].type: REG = r2
		operands[0].access: READ | WRITE
		operands[1].type: REG = r0
		operands[1].access: READ | WRITE
		operands[2].type: REG = r10
		operands[2].access: READ
		operands[3].type: REG = r12
		operands[3].access: READ
	Write-back: True
	Registers read: r2 r0 r10 r12
	Registers modified: r2 r0
	Groups: IsThumb2 

 8  ea fb 0c 7c  umlal	r7, r12, r10, r12
	ID: 500 (uxth)
	op_count: 4
		operands[0].type: REG = r7
		operands[0].access: READ | WRITE
		operands[1].type: REG = r12
		operands[1].access: READ | WRITE
		operands[2].type: REG = r10
		operands[2].access: READ
		operands[3].type: REG = r12
		operands[3].access: READ
	Write-back: True
	Registers read: r7 r12 r10
	Registers modified: r7 r12
	Groups: IsThumb2 

```

**Comment by covanam** [comment]
> I get `W, W, R, R` for the `umull` instruction. Which seems to be correct according to the manual

Sorry, my bad. I gave you the wrong instruction. `umull` is correct, I confused that with `umaal`.

Can you try this `umaal` encoding?

`e3 fb 6c 0c   umaal r0, r12, r3, r12`

You should get `RW RW R R`

Thanks!

**Comment by Rot127** [comment]
Works great!

```
./cstool -d thumb e3fb6c0c
 0  e3 fb 6c 0c  umaal	r0, r12, r3, r12
	ID: 499 (uxtb16)
	op_count: 4
		operands[0].type: REG = r0
		operands[0].access: READ | WRITE
		operands[1].type: REG = r12
		operands[1].access: READ | WRITE
		operands[2].type: REG = r3
		operands[2].access: READ
		operands[3].type: REG = r12
		operands[3].access: READ
	Write-back: True
	Registers read: r0 r12 r3
	Registers modified: r0 r12
	Groups: IsThumb2 HasDSP
```

**Comment by covanam** [comment]
Excellent! I am closing this PR, thanks for your time.

**Pull request closed without merging**
