### PR TITLE
respect libsuffix in pkgconfig

### PR DESCRIPTION
**Pull request by blshkv**
discovered in https://bugs.gentoo.org/677946

### CODE REVIEW

**Comment by aquynh** [comment]
is it better to just use INSTALL_LIB_DIR?

**Comment by blshkv** [comment]
I have pushed a better patch. Basically, the entire lib64 detection was not working on x86 and it was installing it into lib64 on x86 anyway.

I have included the standard GNUInstallDirs which provides all default dirs, you might want to review and remove INSTALL_LIB_DIR altogether.

**Comment by aquynh** [comment]
looks nice, please go ahead replacing all INSTALL_LIB_DIR.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
