### PR TITLE
[next] Add cmake option to tell whether architectures should be included by default

### PR DESCRIPTION
**Pull request by JornVernee**
next branch port of #1463

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
i had to fix this:

- chmod +x
- add #!/bin/sh
- add missing ;; after RISCV line
- correct the check on input architecture 

see https://github.com/aquynh/capstone/commit/8216e8fab8e8ff00bf295d89489b32d2600cddb2

**Comment by JornVernee** [comment]
@aquynh Ok, sorry about that. I used git bash to test the other PR, but kind of eye-balled this one (should have tested as well).

**Comment by aquynh** [comment]
The others had similar problem, i fixed them too :-)

**Pull request merged**
