### PR TITLE
fcomip

### PR DESCRIPTION
**Pull request by mrexodia**
The mnemonic of this instruction was wrong. Intel docs use `fcomip` instead of `fcompi`

---
This change is [Reviewable](https://reviewable.io/reviews/aquynh/capstone/692)

### CODE REVIEW

**Comment by aquynh** [comment]
please provide the hexcode to test this, thanks

**Comment by mrexodia** [comment]
df f1

**Comment by subversor** [comment]
Based on the disassembly, I spent a minute or two of searching for the FCOMPI instruction in my source only to remember it's really FCOMIP! It looks like we have a typo on our hands.

**Comment by aquynh** [comment]
this pull req is incomplete, and you can confirm by disassembling `df f1`: the output is still `fcompi	st(1)`, like before.

**Comment by mrexodia** [comment]
Hm I tested it before but maybe capstone has other references to fcompi? I
did a full text search for fcompi case insensitive through the whole
directory...

**Pull request closed without merging**
