### PR TITLE
Add test with ASAN enabled.

### LINKED ISSUE #2368: [Tests] Add "DIET" CI job
Otherwise it gets broken from time to time.

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Add ASAN builds

It does a few things
- Fixes the `CAPSTONE_DIET` build. Though it is not tested, since we cannot do it with the current test design, which relies on printing everything. 
- Fix a lot of mem leaks,
- Fix the build of `cstest` via `CMakeLists.txt`. This allows now also to enable ASAN for the cstest. Also it is much easier to build `cstest` now.
- Fixes cstest-report.py to work also when `cstest` is installed and in `PATH`.
- Make `run_invalid_cstool.sh` more verbose to help spotting possible ASAN errors.
- Add and fix `tests/cs_details/issue.cs` to the CI.

**Test plan**

CI green (or, if everything fails horribly, mark it optoinal for now)

**Closing issues**

closes https://github.com/capstone-engine/capstone/issues/2368

### CODE REVIEW

**Comment by XVilka** [comment]
@Rot127 please rebase this one, it should fix the redness.

**Comment by Rot127** [comment]
I remove the DIET changes again. Build is still fixed.
They are too complicated to fix for now and not testable. Because we can only test the details and decoding by printing it first, all the test cases of us fail.
So I think if we fix it it should be done once in a separated PR.
Also we can reduce the binary size even more.

**Review by XVilka — APPROVED** [review]
Cool! In the future we also should enable UBSAN, I know there are many potential places that can trigger it. But that's a story for another PR...

**Comment by XVilka** [comment]
@kabeor please take a look and lets merge this quickly, so new PRs will not introduce ASAN warnings.

**Comment by XVilka** [comment]
@kabeor @aquynh

**Comment by XVilka** [comment]
@kabeor while you are online, could you please merge also this one and the LoongArch PRs?

**Review by kabeor — APPROVED** [review]

**Comment by kabeor** [comment]
Great, thanks!

**Pull request merged**
