### PR TITLE
WIP: arch/Sparc: check reg limits when returning reg name

### PR DESCRIPTION
**Pull request by ret2libc**
(patch coming from radare2)

### CODE REVIEW

**Comment by ret2libc** [comment]
I will try to find them, thanks!

**Comment by aquynh** [comment]
Please double check those testcases are still valid, as we fixed many
issues reported by Google Autofuzz recently.

**Comment by ret2libc** [comment]
I'm considering dropping this too, unless @trufae provides any reproducer for this. I think we don't have any in radare2-regressions.

**Comment by ret2libc** [comment]
Let's close this for now. I cannot find any reproducer, we'll reopen if the issue comes up again.

**Pull request closed without merging**
