### PR TITLE
Add X86_REG_EFLAGS to X86_CLC, X86_CLD, X86_CMC

### PR DESCRIPTION
**Pull request by w4kfu**
See https://github.com/aquynh/capstone/pull/800

### CODE REVIEW

**Comment by aquynh** [comment]
are you still missing X86MappingInsn_reduce.inc?

**Comment by w4kfu** [comment]
?

**Comment by aquynh** [comment]
see that file in arch/X86/X86MappingInsn_reduce.inc, for REDUCE mode. this was separated from X86Mapping.c in "master" branch, so you need to fix all your instructions here that you missed so far.

**Comment by w4kfu** [comment]
Should be ok now

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
