### PR TITLE
Fix check target for Unix-like environment

### PR DESCRIPTION
**Pull request by akihikodaki**

### CODE REVIEW

**Comment by aquynh** [comment]
does this fixes something? i can see you are refactoring code, but not sure if it fixes any issues.

**Comment by akihikodaki** [comment]
* Install library to `lib$(LIBNAME).$(VERSION_EXT)` because `install_name` specifies so
* Add `LD_LIBRARY_PATH`

**Comment by aquynh** [comment]
If you run ./make.sh to compile do you still have issues? Which issues?

**Comment by akihikodaki** [comment]
All test linked dynamically fails if `capstone` is not installed. Otherwise it will use library installed to the system.

**Comment by aquynh** [comment]
merged, thanks!

could you please send a pull req for the next branch, too?

**Pull request merged**
