### PR TITLE
Print info

### PR DESCRIPTION
**Pull request by nplanel**
[M68K] remove global dependency aim to have reentrant code
[M68K] Use printer_info to share private info between disassembler and printer

### CODE REVIEW

**Comment by emoon** [comment]
Looks good to me. I think it's a bit unfortunate that we need to call malloc/free for each disassembly call but not sure how to solve it otherwise unless we add some kind of 'cache' or such.

**Comment by emoon** [comment]
If we wanted to we could actually have small cache (MCInst that is being sent here will the same address majority of the time) but it would depend on that we could get a "exit call" when closing down Capstone so we could free the memory. A static cache would work also but then it would set a limit on max number of instances.

**Comment by aquynh** [comment]
If we have to malloc/free on each insn, then something is really wrong i think.

**Comment by nplanel** [comment]
@aquynh I just fixed up the allocation logic as cs_close() cleanup for us.

**Comment by emoon** [comment]
> @aquynh I just fixed up the allocation logic as cs_close() cleanup for us.

:+1:

**Comment by aquynh** [comment]
merged, thanks!

**Comment by emoon** [comment]
Sweet! @aquynh what are the remaining issues now?

**Pull request merged**
