### PR TITLE
fix building on 10.6.8

### PR DESCRIPTION
**Pull request by rpinz**
added __APPLE_CC__ to IS_APPLE test

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
oops, this breaks OS X 10.10.5. i think the way you are combining "-e" with "grep" is not right/supported.

    $ ./make.sh
    ....
    ld: unknown option: -soname
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [libcapstone.so] Error 1

**Comment by zneak** [comment]
The problem is that recent OS Xes define both `__apple_build_version__` and `__APPLE_CC__`, so the command returns 2 instead of 1. The fix is probably to check that $(IS_APPLE) is non-zero instead of exactly one.

Would you (@rpinz) mind fixing it?

**Comment by rpinz** [comment]
Sure, commit incoming.

**Pull request merged**
