### PR TITLE
- Added missing Encoding struct in python bindings

### PR DESCRIPTION
**Pull request by jellever**
Added the x86 encoding structure to the Python bindings

### CODE REVIEW

**Comment by aquynh** [comment]
this is great, thanks! can you please write a sample code with this feature, too?

**Comment by jellever** [comment]
Currently I use it in a tool to automatically generate Yara signature based on binary code/instructions. I use the offset and size information to replace jmp/call adresses with Yara "?" wildcard. 
`md = Cs(CS_ARCH_X86, self.arch)
md.detail = True
md.syntax = CS_OPT_SYNTAX_INTEL
disasm = md.disasm(<code>, <address>)

for ins in disasm:
	x86_data = ins._raw.detail.contents.arch.x86
	ins_hex = str(ins.bytes).encode('hex').upper()
	#use x86_data.encoding.imm_offset and size to replace adresses of jmp/call instructions in ins_hex

**Comment by jellever** [comment]
Will this offset information eventually be merged into master/ next version? Would be very useful for us. @aquynh

**Comment by aquynh** [comment]
Yes, i will merge thus to the next branch, but need more tests before that

**Comment by jellever** [comment]
Cool! If there is anything I can do to speed up the process/ help please let me know!

**Comment by aquynh** [comment]
A big problem is that this move breaks all the bindings because it changes cs_insn struct. If you can fix Python binding (then others), that will be very helpful

**Pull request closed without merging**
