### PR TITLE
added cs_disasm2 with offset parameter to solve issue #1252

### PR DESCRIPTION
**Pull request by KYHSGeekCode**
Sorry for being late, but hope it helps!!!

### CODE REVIEW

**Comment by KYHSGeekCode** [comment]
What are thos fancy checkers?

**Comment by aquynh** [comment]
sorry that i misread the original issue #1252, perhaps due to travelling blur.

in my opinion, a new API is needed only when (1) lots of projects need that, repeatedly (2) it must do significant work so it is worth having, or to expose some internal info from the core, that we cannot access from outside otherwise.

this new API does not satisfy either of the above conditions, unfortunately.

my apologies, again.

**Comment by KYHSGeekCode** [comment]
No, that's ok, and I find your project very USEFUL and willing to help this project when time permits.

**Comment by aquynh** [comment]
close, thanks!

**Pull request closed without merging**
