### PR TITLE
Rewrite make.sh to make it shorter, faster and more portable

### PR DESCRIPTION
**Pull request by radare**
- Remove bashisms (use posix shell)
- Use only two space indentation (no mixed tabs)
- Honor $0 and autogenerate help message
- Correct use of exported and local vars
- Simplify spaguetti (-30LOC)
- Update copyright year
- Quote all vars to avoid command injection
- Cache uname value and allow to override it
- Honor user environment
- Support MAKE_JOBS (by default is 4)

### CODE REVIEW

**Comment by aquynh** [comment]
why did you remove the check for `HOMEBREW_CAPSTONE`? can you put it back?

thanks.

**Comment by radare** [comment]
Whats the point of this variable? As far as i understand is only used when the pkgcfgdir is set, so it does nothing by itself and the current implementation honors the pkgcfgdir env var.

This rewrite needs some testing but it is shorter, more consistent and easier to maintain. Hopefully i didnt broke anything.

**Comment by aquynh** [comment]
On Sat, Feb 28, 2015 at 8:04 PM, radare <notifications@github.com> wrote:

> Whats the point of this variable? As far as i understand is only used when
> the pkgcfgdir is set, so it does nothing by itself and the current
> implementation honors the pkgcfgdir env var.
>

that is only for Brew for some funny weird reasons. i might remove that
altogether later with the related variable in Makefile, but please keep it
for now.


> This rewrite needs some testing but it is shorter, more consistent and
> easier to maintain. Hopefully i didnt broke anything.
>
>
yes it looks much better now. just needs more tests to confirm everything
still works.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by radare** [comment]
Thanks!

**Pull request merged**
