### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by abenkhadra**
Installation instructions for **libjna** on Ubuntu has been added, that would save new comers some time figuring it out :)

### CODE REVIEW

**Comment by aquynh** [comment]
but we already have a line just above it about installing all the required packages including `libjna-java`, no?

**Comment by abenkhadra** [comment]
Sorry, I noticed that just now. I think it would be better to separate JNA installation from JDK since many, like me,  might overlook JDK installation either because they have it already or because it's a bit out-dated v6.

**Comment by aquynh** [comment]
On Wed, Apr 29, 2015 at 11:20 PM, Ammar Ben Khadra <notifications@github.com
> wrote:

> Sorry, I noticed that just now. I think it would be better to separate JNA
> installation from JDK since many, like me, might overlook JDK installation
> either because they have it already or because it's a bit out-dated v6.
>

then feel free to send us another PR, please.

thanks.

**Comment by abenkhadra** [comment]
I've clearly separated the installation of JNA from JDK.

Thanks.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
