### PR TITLE
fix spelling error in comments

### PR DESCRIPTION
**Pull request by bnagy**

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

at the same time, we should also fix the typo in `M68K_AM_IMMIDIATE`? cc @emoon

**Comment by emoon** [comment]
Yeah I can do it later when https://github.com/aquynh/capstone/pull/625 has been merged.

**Comment by aquynh** [comment]
is #625 ready to be merged yet? it is because you said you would still look at that in the last comment ...

**Comment by emoon** [comment]
Yeah but I already merged that in now so it should be ready to go.

**Pull request merged**
