### PR TITLE
ci: use cibuildwheel for python wheels

### PR DESCRIPTION
**Pull request by XVilka**
Beware! Untested!

### CODE REVIEW

**Comment by kabeor** [comment]
Thanks. This will be merged after being tested in my repo.

**Comment by Rot127** [comment]
@kabeor Will you be able to test it in the next two days? Otherwise I'll push a hotfix for https://github.com/capstone-engine/capstone/issues/2102

**Comment by kabeor** [comment]
@Rot127 Actually I'm testing right now:)

**Comment by kabeor** [comment]
Finally... Merged.

**Pull request merged**
