### PR TITLE
PowerShell binding

### PR DESCRIPTION
**Pull request by FuzzySecurity**
Adds the PowerShell binding to Capstone. Feel free to edit as required to match the repo style!

### CODE REVIEW

**Comment by FuzzySecurity** [comment]
A rework of the pull request based on a similar pull request for Keystone.

**Comment by FuzzySecurity** [comment]
@aquynh can you have a look at this. It should be reworked exactly as the Keystone pull request.

The only issue is in "const_generator.py" capstone.h is not included, see my comment.

**Comment by aquynh** [comment]
yes, unlike Keystone, Capstone does not generate symbols from capstone.h, so you need to maintain that yourself. so this is ready to get merged now?

**Comment by FuzzySecurity** [comment]
In that case, I'll put the constants back in the main script if that's ok and revert the other changes. Maybe when I have some spare time I'll try to put together a pull request to add that functionality to "const_generator.py".

**Comment by FuzzySecurity** [comment]
@aquynh I think if you are happy this can be merged now. Screenshot attached!

screen shot 2016-11-11 at 2 25 33 pm

**Comment by aquynh** [comment]
merged, thanks for your amazing work again: https://github.com/aquynh/capstone/commit/d909de00ca32c0e45ab3e6e905f5b851791d0799!

could you port this to the "next" branch (which will be released as v4.0)?

**Comment by FuzzySecurity** [comment]
@aquynh w00t, no problemo, I intend to keep the PowerShell Capstone/Keystone bindings up-to-date with the library as it goes!

**Pull request merged**
