### PR TITLE
detect 64bit library location. compatibility for 64bit systems.

### PR DESCRIPTION
**Pull request by ferdna**
credit goes to Theo. (Theodore Papadopoulo Theodore.Papadopoulo at inria.fr https://cmake.org/pipermail/cmake/2013-July/055374.html)

### CODE REVIEW

**Comment by aquynh** [comment]
merged for both "master" & "next" branches, thanks!

**Comment by lunixbochs** [comment]
this breaks OS X, which does not use a lib64 directory.

**Comment by aquynh** [comment]
i just pushed a commit https://github.com/aquynh/capstone/commit/cbf274c94c9234904f4a12b9a01d4bb2cb21dbc6. can you confirm this fixes MacOS issue?

**Comment by lunixbochs** [comment]
this works for me.

**Comment by aquynh** [comment]
i merged the fix to the "master" branch as well.

this worries me, as we only test this on Mac & some limited Linux distros. any ideas if this still breaks other Linux distros, or *BSD?

**Comment by lunixbochs** [comment]
some linux uses /usr/lib/x86-64-gnu-linux/ instead of lib64.

**Pull request merged**
