### PR TITLE
Honor CS_OPT_UNSIGNED on x86 and add cstool -u

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by aquynh** [comment]
so -u & -d cannot be used at the same time?

**Comment by jpenalbae** [comment]
👍

**Comment by radare** [comment]
The whole argument handling in cstool is pretty weak. I was thinking in rewriting it properly because right now its unmaintainable. Just wanted to add that option to test the change

If you want i can rewrite that cstool mess in a separate pr

**Comment by radare** [comment]
And yep. You cant use -u and -d at the same time, but it was not possible either before :p

**Comment by aquynh** [comment]
merged, thanks!

yes, please fix the argument handling of cstool.

**Comment by radare** [comment]
👍

**Pull request merged**
