### PR TITLE
Make helper functions static to prevent multiple defintions.

### PR DESCRIPTION
**Pull request by Rot127**
See for example: https://github.com/rizinorg/rizin/issues/4183

### CODE REVIEW

**Review by thestr4ng3r — APPROVED** [review]
Confirmed that this fixes the linking issues.

**Review by XVilka — APPROVED** [review]
@kabeor @aquynh please merge this one, it's very important.

The failure is unrelated:
```

Run pipx run --python "C:\hostedtoolcache\windows\Python\3.11.7\x64\python.exe" --spec "D:\a\_actions\pypa\cibuildwheel\v2.14.1" cibuildwheel "bindings/python" --output-dir '"wheelhouse"' --config-file '""' --only '""'
creating virtual environment...
determining package name from 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.14.1'...
creating virtual environment...
installing cibuildwheel from spec 'D:\\a\\_actions\\pypa\\cibuildwheel\\v2.14.1'...
Invalid --only='""', must be a build selector with a known platform
```

**Comment by kabeor** [comment]
https://github.com/capstone-engine/capstone/commit/6a55ef3bdadf606b79a954adad80a90913e6b519 should fix the CI, please push a commit to trigger it.

**Comment by XVilka** [comment]
@kabeor it's green, please merge this one.

**Pull request merged**
