### PR TITLE
x86: fix support for instruction prefetchw

### LINKED ISSUE #1012: x86 prefetch instruction cannot parsing
0F 0D 05 2E 10 00  00  ; prefetch large byte ptr ds:102Eh

>>> pre = ks.asm('prefetch [10000]')
>>> bytecode = bytearray(pre[0])
>>> inst = cs.disasm(bytecode, 0x1000)
>>> print_inst(inst)
>>> pre[0]
[15, 13, 5, 16, 39, 0, 0]

>>> pre = ks.asm('call 0x401000')
>>> bytecode = bytearray(pre[0])
>>> inst = cs.disasm(bytecode, 0x1000)
>>> print_inst(inst)
call    0x402000
>>> pre[0]
[232, 251, 15, 64, 0]

cstool x32 0F0D052E100000
ERROR: invalid assembly code

### PR DESCRIPTION
**Pull request by abenkhadra**
This PR fixes capstone's support for instruction `prefetchw`. The instruction ID has been moved to be at the beginning of Table1852 in `X86GenDisassemblerTables.inc`. I only swapped first and second elements. Also, eflag modification is fixed in `X86MappingInsnOp.inc`.

Sample hex code 

```
cstool -d x64 " 0f 0d 44 11 40 "
```

Fixes #1012. On a second look, it seems like this fix was discussed there first.

### CODE REVIEW

**Comment by aquynh** [comment]
Which branch did you use? Can you try with the next branch?

**Comment by abenkhadra** [comment]
I used latest `master`. I checked `next` now and the instruction is supported (assigned to group 3dnow).

**Comment by aquynh** [comment]
I recommend to use "next", which is updated, fixed many things, and quite stable.

**Comment by abenkhadra** [comment]
I will switch my work to `next` in this case. Feel free to close this PR.

**Comment by aquynh** [comment]
close, thanks.

**Pull request closed without merging**
