### PR TITLE
corrected x86 immediate sizes

### PR DESCRIPTION
**Pull request by obs1dium**
A lot of the x86 immediate sizes were incorrect and merely mirrored the size of the target reg/mem operand.

### CODE REVIEW

**Comment by aquynh** [comment]
how did you verify all of these code?

**Comment by obs1dium** [comment]
I did two things: Search/replace for all opcodes that have an immediate size specifier (i8/i16). Then I manually corrected the sizes for the shift/rotate/bit test ops, which only ever use 8-bit immediates.
The changes do not affect immediate sizes for relative calls as mentioned in #525.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by obs1dium** [comment]
Great :)

**Comment by aquynh** [comment]
this actually breaks AND instruction here: https://github.com/aquynh/capstone/issues/529

can you fix it? thanks.

**Comment by aquynh** [comment]
the below patch can fix the issue #259.

--- a/arch/X86/X86ImmSize.inc
+++ b/arch/X86/X86ImmSize.inc
@@ -49,7 +49,7 @@
 {4, X86_AND32mi},
 {1, X86_AND32mi8},
 {4, X86_AND32ri},
-{1, X86_AND32ri8},
+{4, X86_AND32ri8},
 {4, X86_AND64i32},
 {4, X86_AND64mi32},
 {1, X86_AND64mi8},

**Comment by obs1dium** [comment]
Seems like the printer needs to be modified, I'll have a look ASAP.

**Comment by obs1dium** [comment]
I tried fixing the instruction printer: f9183455242c066aba71931ab3848170d6175363
It seems to produce correct output for the cases I tested.
I'm not super happy with it, though. The main issue is that for some instructions there are effectively two immediate sizes - the encoded immediate and the (sign-)extended immediate.

**Comment by aquynh** [comment]
yes, the problem is with instructions with two immediate sizes.

the easiest solution is to revert your former PR, but i am wondering if there is a better way.

**Comment by aquynh** [comment]
i am not entire sure if your printer fix above is correct in all cases, so another way is to extend struct `size_id` at https://github.com/aquynh/capstone/blob/next/arch/X86/X86Mapping.c#L3256 to contain one more size for printer.

**Comment by obs1dium** [comment]
It should be, but yes... Maybe revert the PR until there's a solution that everybody's happy with.

>another way is to extend struct size_id

I thought of that as well, might be the cleanest and quickest way. The actual size could be stored in `cs_x86_encode` as discussed in #520.

**Comment by aquynh** [comment]
i reverted it. lets keep working on this issue to solve it, thanks.

**Pull request merged**
