### PR TITLE
Fix #2101 - Install cs_operand.h as a public header file

### LINKED ISSUE #2101: cs_operand.h outside the include directory, not installed
```
0$ git grep cs_operand
include/capstone/arm.h:#include "../../cs_operand.h"
include/capstone/capstone.h:#include "../../cs_operand.h"
include/capstone/tricore.h:#include "../../cs_operand.h"
0$ find *| grep cs_operand.h
cs_operand.h
0$
```
this affects the next branch only
its broken since yesterday, proof https://github.com/radareorg/radare2/actions/runs/5611685725/job/15203733000

### PR DESCRIPTION
**Pull request by Rot127**
closes #2101

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@trufae take a look please

**Comment by kabeor** [comment]
Thanks.

**Comment by trufae** [comment]
I can confirm the fix thanks! but the CI is showing some unrelated warnings that should be fixed too

```
 CC      cstool_arm.o
cstool_arm.c: In function ‘print_insn_detail_arm’:
cstool_arm.c:67:45: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   67 |     printf("\t\toperands[%u].type: P-IMM = %u\n", i, op->imm);
      |                                            ~^        ~~~~~~~
      |                                             |          |
      |                                             |          int64_t {aka long int}
      |                                             unsigned int
      |                                            %lu
cstool_arm.c:70:45: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   70 |     printf("\t\toperands[%u].type: C-IMM = %u\n", i, op->imm);
      |                                            ~^        ~~~~~~~
      |                                             |          |
      |                                             |          int64_t {aka long int}
      |                                             unsigned int
      |                                            %lu
  CC      cstool_tms320c64x.o
  CC      cstool.o
  CC      cstool_mos65xx.o
  CC      cstool_x86.o
  CC      cstool_sh.o
  CC      cstool_wasm.o
  CC      cstool_systemz.o
  CC      cstool_mips.o
  LINK    cstool
make[1]: Leaving directory '/home/runner/work/radare2/radare2/capstone/cstool'
make -C tests
make[1]: Entering directory '/home/runner/work/radare2/radare2/capstone/tests'
  CC      test_basic.o
  CC      test_detail.o
  CC      test_skipdata.o
  CC      test_iter.o
  CC      test_customized_mnem.o
  CC      test_arm.o
  CC      test_arm64.o
  CC      test_m68k.o
test_arm.c: In function ‘print_insn_detail’:
test_arm.c:58:45: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   58 |     printf("\t\toperands[%u].type: IMM = 0x%x\n", i, op->imm);
      |                                            ~^        ~~~~~~~
      |                                             |          |
      |                                             |          int64_t {aka long int}
      |                                             unsigned int
      |                                            %lx
test_arm.c:85:45: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   85 |     printf("\t\toperands[%u].type: P-IMM = %u\n", i, op->imm);
      |                                            ~^        ~~~~~~~
      |                                             |          |
      |                                             |          int64_t {aka long int}
      |                                             unsigned int
      |                                            %lu
test_arm.c:88:45: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   88 |     printf("\t\toperands[%u].type: C-IMM = %u\n", i, op->imm);
      |                                            ~^        ~~~~~~~
      |                                             |          |
      |                                             |          int64_t {aka long int}
      |                                             unsigned int
      |                                            %lu
```

**Comment by Rot127** [comment]
@trufae https://github.com/capstone-engine/capstone/pull/2109

**Comment by trufae** [comment]
That was fast

**Pull request merged**
