### PR TITLE
Rename test.c to test_basic.c with corresponding executable name change.

### PR DESCRIPTION
**Pull request by nbriggs**
Fixes CMake target.  Doesn't address necessary xcode project and Visual Studio changes.

### CODE REVIEW

**Comment by aquynh** [comment]
oh right, we have to fix xcode & msvc projects, or they will break.

**Comment by nbriggs** [comment]
I'm working on the XCode part -- I think I've got that, but it's not pushed to my fork/branch yet... the pull request was premature.   I'm also fixing things I missed in the Makefile and tests/Makefile and ensuring that "make check" still works :-(

**Comment by nbriggs** [comment]
And if we're going to be pedantic... I should also fix the corresponding "test" in bindings/ocaml and bindings/python.

**Comment by nbriggs** [comment]
So I *think* that this is now complete -- I'd really appreciate it if someone with ocaml installed could check the tests, and someone with MS Visual Studio could check that the changes in the capstone.sln and related files are OK.

**Comment by aquynh** [comment]
merged, thanks!

@quangnh89, could you give a hand here: can you compile msvc/capstone.sln (master branch) & confirm that there is no issues?

**Comment by quangnh89** [comment]
It looks good! There is no issues.

**Comment by nbriggs** [comment]
Great.   Thanks for merging it, and thanks for letting me know it worked.

-- Nick

**Pull request merged**
