### PR TITLE
Move functionality from make.sh to Makefile

### PR DESCRIPTION
**Pull request by stephengroat**
simplifies builds, prevents overriding of options

### CODE REVIEW

**Comment by stephengroat** [comment]
wait for #1023 to be merged first

**Comment by aquynh** [comment]
merged, thanks!

please do this for "next", too.

**Comment by aquynh** [comment]
we have a problem on Mac now, can you please take a look?

https://travis-ci.org/aquynh/capstone/jobs/379974501

**Comment by stephengroat** [comment]
@aquynh https://github.com/aquynh/capstone/pull/1138#issuecomment-389705113

that's a problem with the remote `brew` formula. i've added `pkg-config` as a build dependency, see https://github.com/Homebrew/homebrew-core/pull/27959

**Pull request merged**
