### PR TITLE
Rewrite str_replace using snprintf for security and fix clang-tidy

### PR DESCRIPTION
**Pull request by jiegec**
**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every API function and struct this PR changes.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Avoid potential integer underflow in `strlen(target) - strlen(str1) + strlen(str2)` if `strlen(str1)` is very large. Use `snprintf` to ensure memory safety.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by Rot127 — APPROVED** [review]

**Comment by Rot127** [comment]
Almost forgot. Please change the doxygen comment of the function to use `///` instead of `//`

**Comment by jiegec** [comment]
> Almost forgot. Please change the doxygen comment of the function to use `///` instead of `//`

Done

**Review by Rot127 — APPROVED** [review]

**Comment by XVilka** [comment]
@kabeor, could you take a quick look at this one? To unblock further LoongArch work?

**Review by kabeor — APPROVED** [review]
Cool, thanks!

**Pull request merged**
