### PR TITLE
Add `#` prefix to tricore imm operand

### PR DESCRIPTION
**Pull request by b1llow**
When I regenerate the `inc` file all the `TRICORE_*` enumerations become `TriCore_*`.

I guess this is the change we want?

Or should I use an older version of llvm-tblgen?

### CODE REVIEW

**Comment by b1llow** [comment]
@Rot127
cc @XVilka

**Review by XVilka — APPROVED** [review]
LGTM. Lets see what @kabeor and @arkup think

**Comment by arkup** [comment]
> LGTM. Lets see what @kabeor and @arkup think

Looks good, thanks, but I will be able to do the test later since I'm a bit short on time now

**Review by Rot127 — APPROVED** [review]
> When I regenerate the inc file all the TRICORE_* enumerations become TriCore_*.
> I guess this is the change we want?

It became clear that doing this for `AArch64` would be a nightmare.
So it's reverted.
Let's see what @aquynh  and @kabeor say (because this change should probably be in the release).
The commit of this change ist:
https://github.com/capstone-engine/llvm-capstone/commit/c9f2924df94b4771beea968f81149d2a7faf9fcb

**Comment by b1llow** [comment]
> > When I regenerate the inc file all the TRICORE_* enumerations become TriCore_*.
> 
> > I guess this is the change we want?
> 
> 
> 
> It became clear that doing this for `AArch64` would be a nightmare.
> 
> So it's reverted.
> 
> Let's see what @aquynh  and @kabeor say (because this change should probably be in the release).
> 
> The commit of this change ist:
> 
> https://github.com/capstone-engine/llvm-capstone/commit/c9f2924df94b4771beea968f81149d2a7faf9fcb
> 
> 

I found a lot of breaking changes but I'm too lazy to adapt for now, so I used the old version of 'llvm-tblgen'.

**Comment by kabeor** [comment]
@imbillow Just keep it in uppercase. LGTM. So is this PR ready to be merged?

**Comment by b1llow** [comment]
> @imbillow Just keep it in uppercase. LGTM. So is this PR ready to be merged?

Probably better to wait for @arkup to do some additional testing, although I tested it and it passes the existing tests.

**Comment by arkup** [comment]
OK I cloned from @imbillow repo and in my application everything is good, correct tricore code and formatting, thanks guys

**Comment by XVilka** [comment]
@kabeor @aquynh it's ready to be merged then.

**Comment by kabeor** [comment]
Great, merged.

**Pull request merged**
