### PR TITLE
Update SystemZ

### PR DESCRIPTION
**Pull request by mephi42**
I managed to import SystemZ definitions from the new LLVM by patching tablegen.
The code is not tested extensively, but some of the new stuff appears to be working:

```
$ cstool/cstool systemz "e700f3580802"
 0  e7 00 f3 58 08 02  	vleg	%v16, 0x358(%r15), 0
```

tablegen patches and instructions are included in this commit in order to simplify similar updates in the future.

### CODE REVIEW

**Comment by aquynh** [comment]
nice work! please provide the LLVM commit you used.

**Comment by mephi42** [comment]
I used `c13d5969^`. https://github.com/llvm-mirror/llvm/commit/c13d5969 itself slightly changed the decode table format, so Captsone's `emitDecodeInstruction` needs to be changed accordingly.

**Comment by XVilka** [comment]
Related https://github.com/aquynh/capstone/issues/563

**Comment by mephi42** [comment]
* Fixed backward compatibility issues: all the old `SYSZ_INS_*` are still valid now.
* Updated all bindings.
* Split into 2 patches: tablegen stuff and the actual update.

**Comment by mephi42** [comment]
* Fixed all sorts of external mappings in `systemz.h` and `SystemZMapping.c`.
* Used with a large instruction trace without problems, so the code looks ready as far as I'm concerned.

**Comment by mephi42** [comment]
* Make sure existing public enums keep their values in order to maintain
  binary backward compatibility.
* Split SystemZGenInsnNameMaps.inc refactoring into a separate patch.
* Map IPTEOptOpt to IPTE.

**Comment by XVilka** [comment]
Is this going to be merged before v4 release?

**Comment by mephi42** [comment]
* Removed accidentally committed SystemZGenInsnNameMaps.inc.new and SystemZGenInsnNameMaps.inc.old files.

**Comment by XVilka** [comment]
@aquynh ping?

**Comment by mephi42** [comment]
Rebased, resolved conflicts in PPC bindings by taking the updated master variants.

**Comment by aquynh** [comment]
is this from the same LLVM commit?

please add your name to CREDITS.TXT

**Comment by mephi42** [comment]
Yes, unfortunately I didn't have time yet to catch up with the LLVM decoder updates.

I've added LLVM commit has to the commit message, and updated CREDITS.TXT.

**Comment by aquynh** [comment]
merged into https://github.com/aquynh/capstone/tree/sysz branch. i will look closer before merging this into master.

thanks!

**Comment by XVilka** [comment]
So? Did you look closer already? Maybe it is time to merge it to the master finally?

**Comment by mephi42** [comment]
I tried using the updated code with angr, and noticed that while op_strs
are correct, all mnemonics are empty.  It boils down to an extra leading
tab in op_str that Tablegen generates:

```
--- a/arch/SystemZ/SystemZGenAsmWriter.inc
+++ b/arch/SystemZ/SystemZGenAsmWriter.inc
@@ -10633,8 +10633,6 @@ static void printInstruction(MCInst *MI, SStream *O, MCRegisterInfo *MRI)
     0U,<------>// ZAP
   };

-  SStream_concat0(O, "\t");
-
   // Emit the opcode for the instruction.
   uint64_t Bits = 0;
   Bits |= (uint64_t)OpInfo0[MCInst_getOpcode(MI)] << 0;
```

I will update my branch and open a new pull request.

**Pull request closed without merging**
