### PR TITLE
arm: treat ARM address as unsigned

### PR DESCRIPTION
**Pull request by akihikodaki**
It should be unsigned because:
* It does arithmetic operations
* Format strings have "%u" instead of "%d"

See also #761.

### CODE REVIEW

**Comment by aquynh** [comment]
again, this sample still produces `blx    	#0x80001024`, without your patch. i mean you should have an example that shows your change makes a difference.

**Comment by akihikodaki** [comment]
It does for me. The result may be different because it causes undefined behavior to cast too large number to `int32_t`. You may be able to reproduce the issue if you change your compiler.

**Comment by aquynh** [comment]
Hmm this makes no sense to me. The output should be the same, regardless of
compiler (??)

**Comment by akihikodaki** [comment]
It can be anything. That's undefined behavior in C language.

**Comment by aquynh** [comment]
what is your OS, and your compiler?

**Comment by akihikodaki** [comment]
See also https://github.com/aquynh/capstone/pull/761#discussion_r77428203.

```
$ cat /etc/os-release
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160802 (GCC)
```

**Comment by akihikodaki** [comment]
It may also depend on the architecture (x86 or x86_64).
```
$ uname -srvmo
Linux 4.7.2.201608211829-1-grsec #1 SMP PREEMPT Sun Aug 21 21:25:45 EDT 2016 x86_64 GNU/Linux
```

**Comment by aquynh** [comment]
What is your output (without your fix)?

**Comment by akihikodaki** [comment]
It succeeds if capstone is installed to the system.
```
$ make check
Check test ...
OK
Check test_detail ...
OK
Check test_arm ...
OK
Check test_arm64 ...
OK
Check test_mips ...
OK
Check test_ppc ...
OK
Check test_sparc ...
OK
Check test_systemz ...
OK
Check test_x86 ...
OK
Check test_xcore ...
OK
Check test_iter ...
OK
Check test.static ...
OK
Check test_detail.static ...
OK
Check test_arm.static ...
OK
Check test_arm64.static ...
OK
Check test_mips.static ...
OK
Check test_ppc.static ...
OK
Check test_sparc.static ...
OK
Check test_systemz.static ...
OK
Check test_x86.static ...
OK
Check test_xcore.static ...
OK
Check test_skipdata ...
OK
Check test_skipdata.static ...
OK
Check test_iter.static ...
OK
```
It fails if capstone is not installed.
```
$ sudo mv /usr/lib/libcapstone.so.3 /usr/lib/_libcapstone.so.3
$ make check
Check test ...
./tests/test: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_detail ...
./tests/test_detail: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_arm ...
./tests/test_arm: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_arm64 ...
./tests/test_arm64: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_mips ...
./tests/test_mips: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_ppc ...
./tests/test_ppc: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_sparc ...
./tests/test_sparc: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_systemz ...
./tests/test_systemz: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_x86 ...
./tests/test_x86: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_xcore ...
./tests/test_xcore: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_iter ...
./tests/test_iter: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test.static ...
OK
Check test_detail.static ...
OK
Check test_arm.static ...
OK
Check test_arm64.static ...
OK
Check test_mips.static ...
OK
Check test_ppc.static ...
OK
Check test_sparc.static ...
OK
Check test_systemz.static ...
OK
Check test_x86.static ...
OK
Check test_xcore.static ...
OK
Check test_skipdata ...
./tests/test_skipdata: error while loading shared libraries: libcapstone.so.3: cannot open shared object file: No such file or directory
FAILED
Check test_skipdata.static ...
OK
Check test_iter.static ...
OK
```

**Comment by aquynh** [comment]
Did you mean the output above for issue #763?

**Comment by akihikodaki** [comment]
Oh, right. Sorry, I'm confused.

**Comment by akihikodaki** [comment]
```
0x80001002:	blx	#0x80001028
	op_count: 1
		operands[0].type: IMM = 0x80001028
```

**Comment by aquynh** [comment]
Oh, this is not like what i expected. What is the output now, with your fix?

**Comment by akihikodaki** [comment]
```
0x80001002:	blx	#0x80001024
	op_count: 1
		operands[0].type: IMM = 0x20
```

**Comment by akihikodaki** [comment]
Let me explain the bug. `_ALIGN_DOWN` is defined as following:
```
#define _ALIGN_DOWN(v, align_width) ((v/align_width)*align_width)
```

So expression `imm = _ALIGN_DOWN(imm, 4);` will expaned like this:
```
imm = imm/4*4;
```

Consider about the value of `imm/4` when imm is 0x80001002. `/` operator generates the floor of the division, 0x20000400.8, so it is expected to be 0x20000400. However, if imm is signed 0x20000401 is less than 0x20000400. Considering that, the floor would be 0x20000251.

0x20000401 would be multiplied by 4 and imm would eventually be 0x80001004 in the expression though 0x80001000 is expected.

**Comment by aquynh** [comment]
this made a change to `test_arm.c`. can you also make the similar change to `bindings/python/test_arm.py`?

**Comment by akihikodaki** [comment]
c2cdb006fd8edc3b41fa0fabf39f9b99f8f64526: Updated `bindings/python/test_arm.py`

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
would you mind sending this same fix for the "next" branch?

**Pull request merged**
