### PR TITLE
Bug fix for incorrect operand type in certain load/store instructions…

### PR DESCRIPTION
**Pull request by andrewcalvano**
This pull request is to resolve issue #863.

### CODE REVIEW

**Comment by aquynh** [comment]
this looks nice, but for the record, can you provide an input (in binary hex form) related to this?

**Comment by andrewcalvano** [comment]
Sure, here is an example of an stp instruction that was not creating operands properly before this update.

STP X7, X8, [X6]

The hex string is: "\xC7\x20\x00\xA9"

Another example of an ldrb instruction that had the same problem:

LDRB W3, [X1]

The hex string is: "\x23\x00\x40\x39"

**Comment by aquynh** [comment]
before this update, we have:

```
$ cstool -d arm64 "\x23\x00\x40\x39"
0  23004039  ldrb	w3, [x1]
	op_count: 2
		operands[0].type: REG = w3
		operands[0].access: WRITE
		operands[1].type: REG = x1
		operands[1].access: READ | WRITE
	Registers read: x1
	Registers modified: w3 x1
```

after this, we have:

```
$ cstool -d arm64 "\x23\x00\x40\x39"
0  23004039  ldrb	w3, [x1]
	op_count: 2
		operands[0].type: REG = w3
		operands[1].type: MEM
			operands[1].mem.base: REG = x1
```

so while this fixes the memory operand, the register read/modified info is gone.

if you can fix that, go ahead updating this PR.
otherwise, i can fix that but it will take a bit longer because i am travelling.

**Comment by andrewcalvano** [comment]
I have been busy as well so haven't had a whole lot of time to look further at this. However, I did find out something potentially interesting.

I was testing this with cstool on 4.0-alpha5 and get the following output

<pre>
$ ./cstool/cstool -d arm64 "\x23\x00\x40\x39"
0  23004039  ldrb	w3, [x1]
	op_count: 2
		operands[0].type: REG = w3
		operands[0].access: WRITE
		operands[1].type: MEM
			operands[1].mem.base: REG = x1
		operands[1].access: READ | WRITE
	Registers read: x1
	Registers modified: w3
</pre>

Were there changes on master that would affect the registers read/modified since the 4.0-alpha5 release?

**Comment by aquynh** [comment]
you are right, i wrongly tested it with the "next" branch.

merged to both "master" & "next" branches, thanks!

**Pull request merged**
