### PR TITLE
Add ARM64, System Z & PowerPC CI

### PR DESCRIPTION
**Pull request by XVilka**
For more information see [Multiarchitecture support](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support) and [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog posts from Travis CI.

Checking on these architectures will help eliminate endianess/portability problems in the code.

### CODE REVIEW

**Comment by aquynh** [comment]
@stephengroat please ack.

**Comment by stephengroat** [comment]
@aquynh travis no longer seems to be running. maybe go through the signup steps again on this account to reenable it?

**Comment by XVilka** [comment]
It's still triggered, but there is no "feedback" into the pull requests/commits from it: https://github.com/aquynh/capstone/issues/1575

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
