### PR TITLE
Integrate into travis cli

### PR DESCRIPTION
**Pull request by HarDToBelieve**

### CODE REVIEW

**Comment by david942j** [comment]
#1355 can be closed after this pr being merged

**Comment by aquynh** [comment]
merged, thanks for this amazing work!

**Comment by aquynh** [comment]
> #1355 can be closed after this pr being merged

that test-mc.sh is a bit different: it compares our output with LLVM, but actually LLVM is "wrong" on many cases. while cstest is to check with our verified output, and make sure we dont regress (with issues.cs)

but we can close that #1355 if there is no longer mismatch.

**Comment by david942j** [comment]
But if we don't expect Capstone to match llvm's output (currently), the issue can be closed since the mismatching is expected.

**Pull request merged**
