### PR TITLE
Add thumb instructions to jump group

### PR DESCRIPTION
**Pull request by abenkhadra**
Added the following thumb instructions to ARM_GRP_JUMP:
* ARM_tB
* ARM_tBL
* ARM_tBLXi
* ARM_tBLXr
* ARM_tBX
* ARM_tBcc
* ARM_tCBNZ
* ARM_tCBZ

### CODE REVIEW

**Comment by abenkhadra** [comment]
I noticed that some jump instructions can be found in rel_branch. Therefore, I updated PR to add only three instructions and fixed a bug.

**Comment by aquynh** [comment]
sorry for the late reply, as i am busy recently.

there is one issue with this fix: actually group ARM_GRP_JUMP is dynamically generated at run-time using `branch` and `indirect_branch` fields of `insn_map` struct in `insns` array. see https://github.com/aquynh/capstone/blob/master/arch/ARM/ARMMapping.c#L13570

so would you please help here: removing all the ARM_GRP_JUMP groups in `insns`, and fix `branch` and `indirect_branch` fields instead. after that, ARM_GRP_JUMP will be generated properly.

thanks.

**Comment by abenkhadra** [comment]
Fixed. Now all jump instructions are handled consistently. To check whether an instruction is jump or not one only needs to check the last group to be ARM_GRP_JUMP.

**Comment by abenkhadra** [comment]
Fixed. The following jump instructions are always direct:
- B
- BL
- CB(N)Z

The following jump instructions are always indirect:
- BX
- BXJ
- TBB/TBH

What is left is BLX which can be both direct and indirect. It easy to guess `ARM_BLXi`. However, I'm not quite sure which one of `ARM_BLX` and  `ARM_BLX_pred` is indirect.

**Pull request closed without merging**
