### PR TITLE
Update SystemZ [part 2]

### PR DESCRIPTION
**Pull request by mephi42**
Continuation of https://github.com/aquynh/capstone/pull/1230

I've found and fixed a bug that caused mnemonic field to be empty.
Here is the simplified diff since the last time:

```
diff --git a/arch/SystemZ/SystemZGenAsmWriter.inc b/arch/SystemZ/SystemZGenAsmWriter.inc
index b4f5dc2e..bdc3a5aa 100644
--- a/arch/SystemZ/SystemZGenAsmWriter.inc
+++ b/arch/SystemZ/SystemZGenAsmWriter.inc
@@ -10633,8 +10633,6 @@ static void printInstruction(MCInst *MI, SStream *O, MCRegisterInfo *MRI)
     0U,	// ZAP
   };

-  SStream_concat0(O, "\t");
-
   // Emit the opcode for the instruction.
   uint64_t Bits = 0;
   Bits |= (uint64_t)OpInfo0[MCInst_getOpcode(MI)] << 0;
diff --git a/contrib/sysz_update/0005-capstone-generate-GenAsmWriter.inc.patch b/contrib/sysz_update/0005-capstone-generate-GenAsmWriter.inc.patch
index a4b23347..cd1353eb 100644
--- a/contrib/sysz_update/0005-capstone-generate-GenAsmWriter.inc.patch
+++ b/contrib/sysz_update/0005-capstone-generate-GenAsmWriter.inc.patch
@@ -71,9 +71,7 @@ index 3c4c9c8e5c6..15c030d662e 100644
    }

    // Emit the initial tab character.
-+#ifdef CAPSTONE
-+  O << "  SStream_concat0(O, \"\\t\");\n\n";
-+#else
++#ifndef CAPSTONE
    O << "  O << \"\\t\";\n\n";
 +#endif
```

### CODE REVIEW

**Comment by XVilka** [comment]
@aquynh hopefully this one and its parent will make it into version 4.0...

**Comment by radare** [comment]
ping @aquynh this should be in the v4 release

**Comment by aquynh** [comment]
@mephi42, thanks so much for your amazing work!

i am still reviewing this pull req. done soon.

@radare definitely, but since now is close to 4.0 release, i think it is better to push this to v4.1.

**Comment by aquynh** [comment]
merged into the "next" branch, which targets v4.1.

thanks!

**Pull request closed without merging**
