### PR TITLE
AArch64 compatibility header

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Based on: https://github.com/capstone-engine/capstone/pull/2296

Adds an additional compatibility option for projects which want to use the `ARM64` naming scheme.

**Todo**

- [x] Generate this header with auto-sync scripts.
- [x] Add docs about it in the release notes.

This adds a compatibility header which defines every public `AArch64` identifier again with the `ARM64` prefix.

**Test plan**

- [x] Add example build test.

**Closing issues**

None

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Should the documentation about release changes updated then too?

**Comment by Rot127** [comment]
wdym? The v6 release notes are updated as well. See https://github.com/capstone-engine/capstone/pull/2321/commits/d6e8f01cb881bb6f341e1ec669401605b1db274f

**Review by XVilka — APPROVED** [review]
Sorry, missed that change. LGTM then.

**Comment by XVilka** [comment]
@kabeor @aquynh so, what was decided on this one?

**Comment by XVilka** [comment]
@kabeor @aquynh could you please look at this one? It's very important as was discussed before.

**Review by kabeor — APPROVED** [review]
LGTM, merged!

**Pull request merged**
