### PR TITLE
Fix ARM operand subtracted field

### PR DESCRIPTION
**Pull request by catenacyber**
Found debugging https://github.com/trailofbits/manticore/issues/514 (and not using fuzzing)

### CODE REVIEW

**Comment by aquynh** [comment]
can you provide an input to test this bug?

**Comment by catenacyber** [comment]
`ldrd r2, r3, [r0], #8`or in hexa `d820c0e0`

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
i merged this into the next branch, too.

**Pull request merged**
