### PR TITLE
RISC-V CSR output

### PR DESCRIPTION
**Pull request by rth7680**
This fixes e.g.

> `cstool riscv64 "73500034"`

which currenly prints non-ascii garbage

> `cstool riscv64 "73500034" | od -c`
> `0000000       0           7   3       5   0       0   0       3   4    `
> `0000020       c   s   r   w   i  \t   ,       $ 003       $ 003   0  \n`
> `0000040`

which is a combination of printing nothing at all for the csr, and erroneously printing internal operand numbers for aliases.

### CODE REVIEW

**Comment by TobiasFaller** [comment]
@rth7680 Great. That is exactly what I encountered when testing the RISCV-V implementation yesterday. The Python binding fails to parse the resulting string as ASCII and therefore fails too. I hope this gets merged soon.

**Comment by pranith** [comment]
Can you please create a new PR on [libcapstone](https://github.com/libcapstone/libcapstone)?

**Review by pranith — APPROVED** [review]

**Comment by pranith** [comment]
@aquynh LGTM. Please merge.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
