### PR TITLE
[Auto-Sync] LLVM 18 update

### PR DESCRIPTION
**Pull request by Rot127**
# SQUASH ME

commit message:
```
Refactor auto-sync updater

This refactors the auto-sync updater scripts, adds multiple tests and some other smaller things:

- Converts the updater in a proper Python package.
- Renaming was done to fit this new package structure.
- Format code with usort and black and enforce it with the CI.
- Add license information to auto-sync scripts.
- Update tree-sitter-cpp to v20.0.5
- Fix py-tree-sitter version to `< 0.22.0` due to https://github.com/tree-sitter/tree-sitter-cpp/issues/250
- Allow file/dir creation of non existing paths.
- Add CI tests for Patch, inc gen, translation and diff persistence testing.
- Implement editing of diffs with an editor.
- Fix: Add Namespace id also to anonymous enumeration members.
```

**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

For now only fixups and tests for the AS scripts. No changes to the archs

- [ ] ~~Add a Capstone diet build test~~ With arch updates.

**Test plan**

CI green

**Closing issues**

...

### CODE REVIEW

**Comment by Rot127** [comment]
@kabeor Also please take a look at this one. I will add more tests, but implement them together with the arch updates (each in separated PRs).

But this makes already many changes. No need to stack them indefinitely.

**Comment by Rot127** [comment]
@kabeor When you merge, please squash and use the commit message from above

**Comment by Rot127** [comment]
@kabeor Can you please take a look at it. It does a lot of clean ups.

**Comment by kabeor** [comment]
Thanks a lot. I have started the review, will done asap.

**Review by kabeor — APPROVED** [review]

**Comment by kabeor** [comment]
Really nice! Thanks a lot!

**Pull request merged**
