### PR TITLE
Relative branch group

### PR DESCRIPTION
**Pull request by abeaumont**
This is a WIP PR, to receive early feedback, currently done:
* Added the group
* Added support for AArch64, ARM, M68K and X86 architectures

Pending:
* Add support for the rest of architectures
* Add support for bindings

Related with #325, #951 and #958.

If this PR is approved, I'll proceed with pending tasks.

### CODE REVIEW

**Comment by aquynh** [comment]
cool, but what do you think about the name GRP_BRANCH_RELATIVE, associated with GRP_BRANCH? i think putting BRANCH before RELATIVE is better.

**Comment by aquynh** [comment]
this overlaps with #951, and that #951 looks OK to me. any issues for you if i merge that?

**Comment by abeaumont** [comment]
@aquynh I named it more in the line of `branch`, `indirect_branch`, `relative_branch`, but I can rename it. No problem if #951 is merged, I'll rebase and fix any conflicts once #951 is merged.

Thanks for reviewing this. I'll rename the group name and add support for the rest of architectures and bindings then.

**Comment by abeaumont** [comment]
Changed group name and updated description with more supported architectures

**Comment by aquynh** [comment]
this looks good. do you want to get it merged now?

**Comment by abeaumont** [comment]
Yes, it can be merged if you want to, even if support for some architectures and bindings is missing. I can create new pull requests as I complete them.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
