### PR TITLE
Fix #2233

### LINKED ISSUE #2233: [ARM] instr. with pc writes are not part of jump group
An instruction which writes to `pc` should be part of the `jump` group.

Similar logic is added for `pop` instructions which write to `pc` ( https://github.com/capstone-engine/capstone/commit/4fc80d82f9134e5b4ed0173a7c79a9b221c87626)

As an example, this `mov` should be of the `jump` group.

```
./cstool -d thumb 8746
 0  87 46  mov	pc, r0
	ID: 28 (mov)
	op_count: 2
		operands[0].type: REG = r15
		operands[0].access: WRITE
		operands[1].type: REG = r0
		operands[1].access: READ
	Registers read: r0
	Registers modified: r15
	Groups: IsThumb 
```

### PR DESCRIPTION
**Pull request by Rot127**
closes #2233

### CODE REVIEW

**Comment by Rot127** [comment]
@kabeor The Windows wheel broke, can you look into it? Besides that it is green.

**Review by XVilka — APPROVED** [review]
@kabeor @aquynh please merge this one too.

**Comment by kabeor** [comment]
https://github.com/capstone-engine/capstone/commit/6a55ef3bdadf606b79a954adad80a90913e6b519 should fix the CI, please push a commit to trigger it.

**Comment by XVilka** [comment]
@kabeor it's green, please merge this one.

**Pull request merged**
