### PR TITLE
arm64: Instructions added in ARMv8.1/2

### PR DESCRIPTION
**Pull request by semihalf-oleksy-michalina**
PR as truafe asked.

```
I've noticed that some instructions added in ARMv8.1/2 are not supported yet.
I made changes in the files that could be edited manually yet I've seen several posts indicate that you edit some table gen files by hand and there is no public info on how to perform such changes.

I can do it myself in case I missed appropriate info - otherwise above I've linked to the branch that has them listed so that it would be easier for you to add new instructions.

(all the changes were based on arm manuals)
```

### CODE REVIEW

**Comment by aquynh** [comment]
great work!

for the record, can you provide hex input for the instructions you added?
-- 
Thanks,
Quynh

http://www.keystone-engine.org
http://www.capstone-engine.org
http://www.unicorn-engine.org

**Comment by semihalf-oleksy-michalina** [comment]
Sure I can. Do you mean something like `A64SysReg_MDCCSR_EL0        = 0x9808, // 10  011  0000  0001  000` in registers?
What file should I edit to add hex input for instructions? (I can't find it myseld, maybe I'm missing something).

**Comment by aquynh** [comment]
no, what i mean is that you can paste some sample instructions you added with hexcode here.
something like:

```
nop = 1f 20 03 d5
```

**Comment by aquynh** [comment]
btw, there is a conflict with `arch/AArch64/AArch64BaseInfo.h`. looks like you based on older code?

another thing: this PR is for the master branch. can you redo this by making a PR for the "next" branch instead?

**Comment by jdiamondGitHub** [comment]
Any news on the instruction updates?  I didn't see any of the new names in the current master code.  Also, is there support for Neon or SVE instruction in AARCH64?

**Comment by XVilka** [comment]
@semihalf-oleksy-michalina ping? can you please update your PR? Would be awesome to have it in the 2.7.0 r2 release.

**Comment by XVilka** [comment]
Ping?

**Comment by XVilka** [comment]
Please also add support for ARMv8.3 instructions too https://community.arm.com/processors/b/blog/posts/armv8-a-architecture-2016-additions

**Comment by XVilka** [comment]
And also ARMv8.4 https://reviews.llvm.org/D48625

**Comment by radare** [comment]
it's pretty sad that this PR was open a year ago and there are still no ways to get in sync with latest llvm, or even was merged. How long should we wait if the project can't keep in sync with llvm and hasnt been any release in more than 3 years to consider Capstone dead?

**Comment by blacktop** [comment]
And also ARMv8.5 - https://community.arm.com/processors/b/blog/posts/arm-a-profile-architecture-2018-developments-armv85a 

I ❤️ Capstone

**Comment by radare** [comment]
> On 21 Oct 2018, at 17:20, E:V:A <notifications@github.com> wrote:
> 
> @radare
> 
> it's pretty sad that this PR was open a year ago and there are still no ways to get in sync with latest llvm, or even was merged. How long should we wait if the project can't keep in sync with llvm and hasnt been any release in more than 3 years to consider Capstone dead?
> 
> It may very well be that @aquynh has tired being the lone maintainer of this great but free project.
> Perhaps he should add a BIG tag in the GitHub README asking for maintenance help?
> 

Do you use telegram or irc? Can we chat somewhere?

**Comment by blacktop** [comment]
Let's get this shizz merged in ya'll.  Please see this https://github.com/aquynh/capstone/pull/1287

**Comment by XVilka** [comment]
@blacktop beware that it makes sense to add 8.4 and 8.5 while you are on it: https://github.com/llvm-mirror/llvm/search?q=%5BAArch64%5D%5Bv8.5A%5D&type=Commits

**Comment by aquynh** [comment]
i cleaned up this to solve some conflicts, and merged into the https://github.com/aquynh/capstone/tree/arm64 branch. look closer, i think something is not right: this adds some new instructions, but also all the variations. for example, perhaps some of the below instructions can map into one, reducing number of instructions we will support?

```
    ARM64_INS_LDEORB,
    ARM64_INS_LDEORAB,
    ARM64_INS_LDEORALB,
    ARM64_INS_LDEORLB,
    ARM64_INS_LDEORH,
    ARM64_INS_LDEORAH,
    ARM64_INS_LDEORALH,
    ARM64_INS_LDEORLH,
    ARM64_INS_LDEOR,
    ARM64_INS_LDEORA,
    ARM64_INS_LDEORAL,
    ARM64_INS_LDEORL,
```

also, this removes ARM64_INS_NEGS & ARM64_INS_NGCS?

**Comment by aquynh** [comment]
this adds some new instructions, but does not update the core logic to handle them, so i doubt that this is a complete work.

**Comment by aquynh** [comment]
supported now in the next branch, thanks.

**Pull request closed without merging**
