### PR TITLE
Sparc conditional branches displacement fix

### PR DESCRIPTION
**Pull request by jpenalbae**
Calls & conditional branches were not decoded properly when using negative displacements.

It might still fail in some cases because sometimes MI->csh->detail is not defined and I cannot figure out if its a conditional branch with prediction or not, so I cannot calculate the displacement size properly...

### CODE REVIEW

**Comment by aquynh** [comment]
(1) can you please provide the input (in hexcode form), so i can test this fix?

(2) What do you mean by "sometimes MI->csh->detail is not defined" ? What input can trigger this problem?

Thanks.

**Comment by aquynh** [comment]
(3) can you double-check to see if this commit can be applied to the `next` branch - without any change?

thanks.

**Comment by jpenalbae** [comment]
I have written this useless code to test conditional branching on radare using capstone disassembler. You can get the hex for the opcodes from radare's output.

```javascript
.section ".text"


main:
   add %g4, 34, %g4

   ! Branch on integer condition (Bicc)
   ba main
   bn main
   bge main
   bl main

   ! Branch on integer condition with prediction (BPcc)
   ba %icc, main
   bn %icc, main
   bge %icc, main
   bl,a,pn %icc, main

   ! Branch on floating point condition (FBfcc)
   fba main
   fbn main
   fbug main
   fbule main

   ! Branch on floating point condition with prediction (FBPfcc)
   fba %fcc0, main
   fbn,a %fcc0, main
   fbug %fcc0, main
   fbule,pn %fcc0, main

   ! Branch on integer register with prediction (BPr)
   brz %g4, main
   brlez %g4, main
   brgz,a %g4, main
   brlz,pn %g4, main

   ! Call with negative displacement
   call main

   inc %g4    
```


Here is radare output using capstone patched with this PR
```
$ r2 -q -c "e asm.lineswidth=20;pd 22" good.o                                                    
Warning: Cannot initialize program headers
   ;      [1] va=0x00000058 pa=0x00000058 sz=92 vsz=92 rwx=-r-x .text
                        ;-- entry0:
                        ;-- sym.main:
                        ;-- section..text:
         ......-...-.-> 0x00000058    88012022     add %g4, 0x22, %g4
         |||||| ||| `=< 0x0000005c    10bfffff     ba 0x58
         |||||| |||,==< 0x00000060    00bffffe     bn 0x58
         |||||| ||`===< 0x00000064    16bffffd     bge 0x58
         |||||| |`====< 0x00000068    06bffffc     bl 0x58
         |||||| `=====< 0x0000006c    104ffffb     ba %icc, 0x58
         ||||||,======< 0x00000070    004ffffa     bn %icc, 0x58
         |||||`=======< 0x00000074    164ffff9     bge %icc, 0x58
         ||||`========< 0x00000078    2647fff8     bl,a,pn %icc, 0x58
         ||||  |   |    0x0000007c    11bffff7     fba 0x58
         ||||  |   |    0x00000080    01bffff6     fbn 0x58
         ||||  |   |    0x00000084    0bbffff5     fbug 0x58
         ||||  |   |    0x00000088    1dbffff4     fbule 0x58
         ||||  |   |    0x0000008c    114ffff3     fba %fcc0, 0x58
         ||||  |   |    0x00000090    214ffff2     fbn,a %fcc0, 0x58
         ||||  |   |    0x00000094    0b4ffff1     fbug %fcc0, 0x58
         ||||  |   |    0x00000098    1d47fff0     fbule,pn %fcc0, 0x58
         |||`=========< 0x0000009c    02f93fef     brz %g4, 0x58
         ||`==========< 0x000000a0    04f93fee     brlez %g4, 0x58
         |`===========< 0x000000a4    2cf93fed     brgz,a %g4, 0x58
         `============< 0x000000a8    06f13fec     brlz,pn %g4, 0x58
               |   |    0x000000ac    7fffffeb     call 0x58
               |   |       0x00000058() ; entry0
```

radare output using capstone without this patch
```
$ r2 -q -c "e asm.lineswidth=20;pd 22" good.o
Warning: Cannot initialize program headers
                        ;-- entry0:
                        ;-- sym.main:
                        ;-- section..text:
                        0x00000058    88012022     add %g4, 0x22, %g4  ; [1] va=0x00000058 pa=0x00000058 sz=92 vsz=92 rwx=-r-x .text
                    ,=< 0x0000005c    10bfffff     ba 0x1000058
                   ,==< 0x00000060    00bffffe     bn 0x1000058
                  ,===< 0x00000064    16bffffd     bge 0x1000058
                 ,====< 0x00000068    06bffffc     bl 0x1000058
                ,=====< 0x0000006c    104ffffb     ba %icc, 0x200058
               ,======< 0x00000070    004ffffa     bn %icc, 0x200058
              ,=======< 0x00000074    164ffff9     bge %icc, 0x200058
             ,========< 0x00000078    2647fff8     bl,a,pn %icc, 0x200058
             ||||||||   0x0000007c    11bffff7     fba 0x3ffff7
             ||||||||   0x00000080    01bffff6     fbn 0x3ffff6
             ||||||||   0x00000084    0bbffff5     fbug 0x3ffff5
             ||||||||   0x00000088    1dbffff4     fbule 0x3ffff4
             ||||||||   0x0000008c    114ffff3     fba %fcc0, 0x7fff3
             ||||||||   0x00000090    214ffff2     fbn,a %fcc0, 0x7fff2
             ||||||||   0x00000094    0b4ffff1     fbug %fcc0, 0x7fff1
             ||||||||   0x00000098    1d47fff0     fbule,pn %fcc0, 0x7fff0
            ,=========< 0x0000009c    02f93fef     brz %g4, 0xffef
           ,==========< 0x000000a0    04f93fee     brlez %g4, 0xffee
          ,===========< 0x000000a4    2cf93fed     brgz,a %g4, 0xffed
         ,============< 0x000000a8    06f13fec     brlz,pn %g4, 0xffec
         ||||||||||||   0x000000ac    7fffffeb     call 0x58
         ||||||||||||      0x00000058() ; entry0
```

**Comment by jpenalbae** [comment]
About MI->csh->detail not defined I mean this:

```c
#include <stdio.h>
#include <capstone/capstone.h>

int main(int argc, const char *argv[])
{
   char *buf = "\x12\x80\x00\x03";
   int mode, ret, n;
   csh handle;
   cs_insn* insn;

   mode = CS_MODE_BIG_ENDIAN | CS_MODE_V9;

   ret = cs_open (CS_ARCH_SPARC, mode, &handle);
   if (ret) {
      printf("Error cs_open()\n");
      return 1;
   }

   cs_option (handle, CS_OPT_DETAIL, CS_OPT_OFF);
   n = cs_disasm (handle, buf, 4, 0, 1, &insn);

   printf("insn->detail: %p\n", insn->detail);

   return 0;
}
```

Detail points to null....
```
$ ./cs 
insn->detail: (nil)
```

if cs_option() uses CS_OPT_OFF, details won't be accessible from printOperand(), and displacement cannot be calculated properly.

There is any way of accessing 'op2' value from printOperand()? Cause that would be a better approach in order to calculate the proper displacement size.

format

I'm using "MI->flat_insn->detail->sparc.op_count" as workaround instead of checking op2 value, cause I don't know if op2 is available anywhere within printOperand function.

**Comment by jpenalbae** [comment]
I have improved the displacement calculation. It would be easier if op2 value would be available, but at least now it works fine even if CS_OPT_DETAIL is set to off.

I will test it tomorrow against 'next' branch, but it should work fine on it.

**Comment by aquynh** [comment]
this change still make sure that we always have absolute address all the time, right?

**Comment by jpenalbae** [comment]
Yes. It always does "imm = instruction address + (instructions displacement * 4)" for every branch instruction and calls.

```c
Imm = (uint32_t)MI->address + Imm * 4;
```

Radare now produces proper output
```
$ r2 -q -c "e asm.lineswidth=20;pd 22" good.o
   ;      [1] va=0x00000058 pa=0x00000058 sz=108 vsz=108 rwx=-r-x .text
                         ;-- entry0:
                         ;-- sym.main:
                         ;-- section..text:
  ..........-...-...-.-> 0x00000058    88012022       add %g4, 0x22, %g4 ; [1] va=0x00000058 pa=0x00000058 sz=108 vsz=108 rwx=-r-x .text
  |||||||||| ||| ||| `=< 0x0000005c    10bfffff       ba 0x58
  |||||||||| ||| |||,==< 0x00000060    00bffffe       bn 0x58
  |||||||||| ||| ||`===< 0x00000064    16bffffd       bge 0x58
  |||||||||| ||| |`====< 0x00000068    06bffffc       bl 0x58
  |||||||||| ||| `=====< 0x0000006c    104ffffb       ba %icc, 0x58
  |||||||||| |||,======< 0x00000070    004ffffa       bn %icc, 0x58
  |||||||||| ||`=======< 0x00000074    164ffff9       bge %icc, 0x58
  |||||||||| |`========< 0x00000078    2647fff8       bl,a,pn %icc, 0x58
  |||||||||| `=========< 0x0000007c    106ffff7       ba %xcc, 0x58
  ||||||||||,==========< 0x00000080    006ffff6       bn %xcc, 0x58
  |||||||||`===========< 0x00000084    166ffff5       bge %xcc, 0x58
  ||||||||`============< 0x00000088    2667fff4       bl,a,pn %xcc, 0x58
  |||||||`=============< 0x0000008c    11bffff3       fba 0x58
  ||||||`==============< 0x00000090    01bffff2       fbn 0x58
  |||||`===============< 0x00000094    0bbffff1       fbug 0x58
  ||||`================< 0x00000098    1dbffff0       fbule 0x58
  |||`=================< 0x0000009c    114fffef       fba %fcc0, 0x58
  ||`==================< 0x000000a0    214fffee       fbn,a %fcc0, 0x58
  |`===================< 0x000000a4    0b4fffed       fbug %fcc0, 0x58
  `====================< 0x000000a8    1d47ffec       fbule,pn %fcc0, 0x58
  =====================< 0x000000ac    02f93feb       brz %g4, 0x58
  =====================< 0x000000b0    04f93fea       brlez %g4, 0x58
  =====================< 0x000000b4    2cf93fe9       brgz,a %g4, 0x58
  =====================< 0x000000b8    06f13fe8       brlz,pn %g4, 0x58
            |   |   |    0x000000bc    7fffffe7       call 0x58
            |   |   |       0x00000058() ; entry0
            |   |   |    0x000000c0    88012001       add %g4, 1, %g4
```

**Comment by aquynh** [comment]
a quick suggestion: you can make your patch more "future-proof" by checking the "public" instruction ID, rather than "internal" ID. for example, rather than checking `SP_BCOND` & `SP_BCONDA` separately, you can map them to the "public" instruction ID `SPARC_INS_B`, then check on `SPARC_INS_B` only.

to do this, rather than looking at `MCInst_getOpcode()` for "internal" instruction ID, look at value of `MI->flat_insn->id` ("public" instruction ID). this is similar to what X86 code is doing: https://github.com/aquynh/capstone/blob/master/arch/X86/X86IntelInstPrinter.c#L582

**Comment by aquynh** [comment]
oh now i see this is what you did in the first PR.

**Comment by aquynh** [comment]
hmm but i think that you can use this same trick, because looks like you can still group related instructions and check on their "public" ID?

**Comment by jpenalbae** [comment]
Yes, I could do that, but we will end up with two nested switches as still we need to check the "internal" id to be able yo select the proper displacement. So I don't see the point in adding two nested switches, It would only increase length and indentation...

As I said, the best way would be to check bits 22 to 24 from the raw instruction, to check op2 field:
op2

But neither raw instruction nor op2 are accessible from printOperand()...

**Comment by aquynh** [comment]
A good thing about nested switch is better performance: the outer switch check for "public" ID, then the inner switch check for "internal" ID. This shortens the total times of check for a random ID.

**Comment by radare** [comment]
two nested switch cases will perform worst than a single one. switch cases are translated as jump tables, so a single one will avoid unnecessary memory reads.

**Comment by aquynh** [comment]
we are doing nested switch on two variables, so it should make the difference.

**Comment by radare** [comment]
wat. anyway those micro optimizations are not going to provide any performance boost. I see the patch correct and clean, despite making it better will require more refactoring on the capstone/llvm code. Which iirc you said you wanted to sync that code from LLVM at some point?

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
picked up this for the `next` branch as well, thanks.

**Comment by jpenalbae** [comment]
Nice, Thank you :)

Whenever I have some spare time I will discuss some other sparc related issues with you.

**Comment by aquynh** [comment]
great! would be awesome if you can look at this issue: https://github.com/aquynh/capstone/issues/280

thanks.

**Pull request merged**
