### PR TITLE
AArch64 update to LLVM 18

### LINKED ISSUE #2268: ARM64: Invalid decoding of constant for predicated instructions `fadd`, `fsub`, `fsubr`, `fmul`, `fmax`, `fmaxnm`, `fmin`, `fminnm`
ARM64 Example hex: `00805865`

When using cstool, the output is:
`fadd  z0.h, p0/m, z0.h, #0.0`

when it should be:
`fadd  z0.h, p0/m, z0.h, #0.5`

There are more instructions (listed below) that have the incorrect interpretation of the `i1` field. The decoder doesn't produce valid constants for those instructions.

[FADD <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fadd_z_p_zs.html)
[FMAX <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fmax_z_p_zs.html)
[FMAXNM <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fmaxnm_z_p_zs.html)
[FMIN <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fmin_z_p_zs.html)
[FMINNM <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fminnm_z_p_zs.html)
[FMUL <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fmul_z_p_zs.html)
[FSUB <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fsub_z_p_zs.html)
[FSUBR <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <const>](https://docsmirror.github.io/A64/2023-06/fsubr_z_p_zs.html)

### LINKED ISSUE #2269: ARM64: Unable to decode `luti2` and `luti4` instructions
When using `cstool`, I'm not able to decode ARM64 `luti2` and `luti4` instructions.

Here are some examples:

Hexcode: `00B02045`
Should output: `luti2   z0.b, { z0.b }, z0[0]`
But `cstool` fails and stops decoding altogether.

Hexcode: `55B17545`
Should output: `luti2   z21.b, { z10.b }, z21[1]`
But again, `cstool` fails and stops decoding.

### LINKED ISSUE #2270: ARM64: Unable to decode `fmlalb`, `fmlalt`, `fmlallbb`, `fmlallbt`, `fmlalltb`, `fmlalltt` instructions
The following instructions are not able to be decoded with `cstool`:

- `FMLALB <Zda>.H, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALT <Zda>.H, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLBB <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLBT <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLTB <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`
- `FMLALLTT <Zda>.S, <Zn>.B, <Zm>.B[<imm>]`

The decoder just fails and stops.

### LINKED ISSUE #2285: [AArch64] SME instructions with  indexed operands do not have correct disassembly information
Working on the latest `next` branch, disassembling a range of SME instructions yields incorrect disassembly information, often with additional memory operands being defined.

It seems to be an issue with the pattern matching of `[...]`. A similar issue occurred when implementing PR #1907 and was fixed in PR #1925. I'm not sure how different the backend is now after the auto-sync update, but perhaps a similar fix can be implemented from this?

Listed below are some examples:

Issue - Operand 2 `p3.s`'s index is identified as an additional memory operand.
```
cstool -d aarch64 67447125
 0  67 44 71 25  psel	p7, p1, p3.s[w13, 1]
	ID: 735 (psel)
	op_count: 4
		operands[0].type: REG = p7
		operands[0].access: WRITE
		operands[1].type: REG = p1
		operands[1].access: READ
		operands[2].type: REG = p3
		operands[2].access: READ
			Vector Arrangement Specifier: 0x20
		operands[3].type: MEM
			operands[3].mem.base: REG = w13
			operands[3].mem.disp: 0x1
	Registers read: p1 p3 w13
	Registers modified: p7
	Groups: HasSVE2p1_or_HasSME
```

Issue - Operand `p4` is mistaken for a memory operand and `x10` as its register offset. Also, operands[0] should not have an access specifier, and operands[2] should not have a vector index
```
cstool -d aarch64 4131a2e0
 0  41 31 a2 e0  st1w	{za0h.s[w13, 1]}, p4, [x10, x2, lsl #2]
	ID: 1047 (st1w)
	op_count: 3
		operands[0].type: SME_MATRIX
		operands[0].sme.type: 2
		operands[0].sme.tile: za0.s
		operands[0].sme.slice_reg: w13
		operands[0].sme.slice_offset: 1
		operands[0].sme.is_vertical: false
		operands[0].access: WRITE
			Vector Arrangement Specifier: 0x20
			Vector Index: 0
		operands[1].type: MEM
			operands[1].mem.base: REG = p4
			operands[1].mem.index: REG = x10
		operands[1].access: WRITE
			Shift: type = 1, value = 2
			Vector Index: 0
		operands[2].type: MEM
			operands[2].mem.base: REG = x2
		operands[2].access: WRITE
			Vector Index: 0
	Registers read: p4 x10 x2
	Groups: HasSME
```

Issue - Same as above.
```
cstool -d aarch64 c0089fe0
 0  c0 08 9f e0  ld1w	{za0h.s[w12, 0]}, p2/z, [x6]
	ID: 434 (ld1w)
	Is alias: 1354 (ld1w) with ALIAS operand set
	op_count: 2
		operands[0].type: SME_MATRIX
		operands[0].sme.type: 2
		operands[0].sme.tile: za0.s
		operands[0].sme.slice_reg: w12
		operands[0].sme.slice_offset: 0
		operands[0].sme.is_vertical: false
		operands[0].access: READ
			Vector Arrangement Specifier: 0x20
			Vector Index: 0
		operands[1].type: MEM
			operands[1].mem.base: REG = p2
			operands[1].mem.index: REG = x6
		operands[1].access: READ
			Vector Index: 0
	Registers read: p2 x6
	Groups: HasSME
```

### LINKED ISSUE #2363: ARM64_REG_Vx vs. ARM64_REG_Qx
For instruction `mov w20, v1.s[0]` (0x0e043c34),

I get the correct information with the version 5.0.0:
```
# cstool -d arm64be 0e043c34
0  0e 04 3c 34  mov    w20, v1.s[0]
        ID: 488 (mov)
        op_count: 2
                operands[0].type: REG = w20
                operands[0].access: WRITE
                operands[1].type: REG = v1
                operands[1].access: READ
                        Vector Arrangement Specifier: 0xb
                        Vector Index: 0
        Registers read: v1
        Registers modified: w20
        Groups: neon
```

Whereas, with the next branch, I get `q1` instead of `v1` for the second operand:
```
# ./cstool/cstool -d aarch64be 0e043c34
0  0e 04 3c 34  mov    w20, v1.s[0]
        ID: 1232 (umov)
        Is alias: 1349 (mov) with ALIAS operand set
        op_count: 2
                operands[0].type: REG = w20
                operands[0].access: WRITE
                operands[1].type: REG = q1
                operands[1].access: READ
                        Vector Arrangement Specifier: 0x20
                        Vector Index: 0
        Registers read: q1
        Registers modified: w20
        Groups: HasNEONorSME
```

Although the names `v1` and `q1` refer to the same register, their interpretations are different (i.e., `q1` as a single 128-bit quantity while `v0` as a vector of something).

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Generated with: https://github.com/capstone-engine/llvm-capstone/pull/45

<details>
<summary>New features/instructions</summary>

New features:

```
AArch64_FEATURE_HasPAuthLR,
AArch64_FEATURE_HasSMEFA64,
AArch64_FEATURE_HasFPMR,
AArch64_FEATURE_HasFP8,
AArch64_FEATURE_HasFAMINMAX,
AArch64_FEATURE_HasFP8FMA,
AArch64_FEATURE_HasSSVE_FP8FMA,
AArch64_FEATURE_HasFP8DOT2,
AArch64_FEATURE_HasSSVE_FP8DOT2,
AArch64_FEATURE_HasFP8DOT4,
AArch64_FEATURE_HasSSVE_FP8DOT4,
AArch64_FEATURE_HasLUT,
AArch64_FEATURE_HasSME_LUTv2,
AArch64_FEATURE_HasSMEF8F16,
AArch64_FEATURE_HasSMEF8F32,
AArch64_FEATURE_HasSVE2orSME2,
AArch64_FEATURE_HasCHK,
AArch64_FEATURE_HasGCS,
AArch64_FEATURE_HasCPA,
```

New instructions:
```
AArch64_INS_ADDPT,
AArch64_INS_AUTIA171615,
AArch64_INS_AUTIASPPC,
AArch64_INS_AUTIB171615,
AArch64_INS_AUTIBSPPC,
AArch64_INS_BF1CVTL2,
AArch64_INS_BF1CVTLT,
AArch64_INS_BF1CVTL,
AArch64_INS_BF1CVT,
AArch64_INS_BF2CVTL2,
AArch64_INS_BF2CVTLT,
AArch64_INS_BF2CVTL,
AArch64_INS_BF2CVT,
AArch64_INS_F1CVTL2,
AArch64_INS_F1CVTLT,
AArch64_INS_F1CVTL,
AArch64_INS_F1CVT,
AArch64_INS_F2CVTL2,
AArch64_INS_F2CVTLT,
AArch64_INS_F2CVTL,
AArch64_INS_F2CVT,
AArch64_INS_FAMAX,
AArch64_INS_FAMIN,
AArch64_INS_FCVTNB,
AArch64_INS_FMLALLBB,
AArch64_INS_FMLALLBT,
AArch64_INS_FMLALLTB,
AArch64_INS_FMLALLTT,
AArch64_INS_FMLALL,
AArch64_INS_FVDOTB,
AArch64_INS_FVDOTT,
AArch64_INS_GCSPOPCX,
AArch64_INS_GCSPOPM,
AArch64_INS_GCSPOPX,
AArch64_INS_GCSPUSHM,
AArch64_INS_GCSPUSHX,
AArch64_INS_GCSSS1,
AArch64_INS_GCSSS2,
AArch64_INS_GCSSTR,
AArch64_INS_GCSSTTR,
AArch64_INS_MADDPT,
AArch64_INS_MADPT,
AArch64_INS_MLAPT,
AArch64_INS_MSUBPT,
AArch64_INS_PACIA171615,
AArch64_INS_PACIASPPC,
AArch64_INS_PACIB171615,
AArch64_INS_PACIBSPPC,
AArch64_INS_PACNBIASPPC,
AArch64_INS_PACNBIBSPPC,
AArch64_INS_RETAASPPC,
AArch64_INS_RETABSPPC,
AArch64_INS_SUBPT,
```
</details>

**Test plan**

- [x] Fix current one.
- [x] Add new MC tests
- [x] Add tests for SME
- [x] Fuzzing

General detail testing comes afterwards, when testing in general is modernized.

**Closing issues**

closes https://github.com/capstone-engine/capstone/issues/2269
closes https://github.com/capstone-engine/capstone/issues/2270
closes https://github.com/capstone-engine/capstone/issues/2268
closes https://github.com/capstone-engine/capstone/issues/2285
closes https://github.com/capstone-engine/capstone/issues/2363

### CODE REVIEW

**Comment by hainest** [comment]
Relative to the [Mar 2024](https://developer.arm.com/Architectures/A-Profile%20Architecture#Software-Download) spec, the system registers listed below don't currently have a representation in Capstone. I've not yet checked to see if they are in LLVM-18's tablegen.

DBGBCR{16-63}_EL1
DBGBVR{16-63}_EL1
DBGWCR{16-63}_EL1
DBGWVR{16-63}_EL1
ICV_AP0R{0-3}_EL1
ICV_AP1R{0-3}_EL1
ICV_BPR1_EL1
ICV_CTLR_EL1
ICV_DIR_EL1
ICV_EOIR{0-1}_EL1
ICV_HPPIR{0-1}_EL1
ICV_IAR{0-1}_EL1
ICV_IGRPEN{0-1}_EL1
ICV_NMIAR1_EL1
ICV_PMR_EL1
ICV_RPR_EL1
SPMEVCNTR{16-63}_EL0
SPMEVFILT2R{16-63}_EL0
SPMEVFILTR{16-63}_EL0
SPMEVTYPER{16-63}_EL0
SP_EL3
TRBMPAM_EL1

**Comment by Rot127** [comment]
Couldn't find them in LLVM with `grep` as well.

**Comment by Rot127** [comment]
I cannot reproduce the fuzzing bug. Locally everything is fine (also no segfault for `0x0->0xffffffff`).

~~My guess is, it is a Python 2 issues. So I'd wait for https://github.com/capstone-engine/capstone/pull/2378 and https://github.com/google/oss-fuzz/pull/12028.~~

clang-tidy fails with a false positive. The code is correct and clang-tidy-19/18 don't give the warning. But `ubuntu-latest` doesn't have clang-tidy-18 as package. So we just need to ignore it for now.

**Comment by FinnWilkinson** [comment]
Hi @Rot127, I'm really keen to see this PR merged into the `next` branch and know that there is a lot of other work that you and others are doing throughout the project. Is there anything I can do to help speed up this PR being merged?

**Comment by Rot127** [comment]
@FinnWilkinson The main thing is the missing review from @kabeor and/or @aquynh. I'm currently off. But will take time in two days to rebase it and address reviewer comments.

**Comment by Rot127** [comment]
@FinnWilkinson Please be aware that we will likely change the enum naming of `AArch64_ -> AARCH64_` in the near future. Just so you are aware of (see: https://github.com/capstone-engine/capstone/pull/2349#discussion_r1641227883). I am sorry for apparently being sloppy and forgot to check it way earlier.

**Comment by Rot127** [comment]
@aquynh @kabeor Please review this. I just rebase it again. The failing tests are explained here: https://github.com/capstone-engine/capstone/pull/2298#issuecomment-2151699039

**Comment by Rot127** [comment]
@aquynh @kabeor Please review this. I just rebase it again. The failing tests are explained here: https://github.com/capstone-engine/capstone/pull/2298#issuecomment-2151699039

**Comment by Rot127** [comment]
@aquynh @kabeor When you review this weekend, you can skip https://github.com/capstone-engine/capstone/pull/2298/commits/0615ebb3cd51d2626d171c5361a87196f1478951.
This one is only the enum name change.

**Review by kabeor — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
