### PR TITLE
update AARCH64 to ARMv8.x

### PR DESCRIPTION
**Pull request by blacktop**
Continuation of #1287

**Using LLVM:** `7.0.1` aka `release_70` *branch*

Rebased on top of "next" branch.

**NOTE:** 
```bash
cp: ~/Projects/github/llvm/build/lib/Target/AArch64/AArch64MappingInsnOp.inc: No such file or directory
cp: ~/Projects/github/llvm/build/lib/Target/AArch64/ARMMappingInsnOp.inc: No such file or directory
```

### CODE REVIEW

**Comment by blacktop** [comment]
Trying to copy @mephi42's #1306

**Comment by blacktop** [comment]
@aquynh I could use a little help with the travis errors.  I believe it is mostly due to me taking @mephi42's patches and just doing a simple find a replace that caused a lot of the errors in `arch/AArch64/AArch64GenDisassemblerTables.inc`

I'm not sure what you want to do with `alias_insn_name_maps` in `arch/AArch64/AArch64Mapping.c` as there were none in the systemZ stuff?

**Comment by aquynh** [comment]
i will work on major update on all archs soon, any progress on this?

**Comment by XVilka** [comment]
LLVM 8.0 will be released quite soon, maybe it make sense to base on top of it, if there are any updates in these files?

**Comment by blacktop** [comment]
@aquynh I apologize for my lack of progress.  I have been extra busy at work lately.  Have you seen the new TravisCI errors?  I cleaned up a lot of them.  Do you have any ideas on how I can remove the remaining?  I will hopefully have time today to dig back into this.

**Comment by blacktop** [comment]
@aquynh I would love more detail on your major updates?  Are you going to try and get back insync with LLVM? So that we wouldn't need to patch the tablegen format?  It also would be good to sync with llvm 8 right?

**Comment by aquynh** [comment]
your work changed all the instructions, but we need to have the postfix removed. by doing that, we can group related instructions to one.

**Comment by aquynh** [comment]
> @aquynh I would love more detail on your major updates? Are you going to try and get back insync with LLVM? So that we wouldn't need to patch the tablegen format? It also would be good to sync with llvm 8 right?

i am not very fond of patching tablegen like this, because that is very fragile, due to tablegen code quick change. so i am writing some tools to convert the original .inc files to Capstone .inc files.

for now, i base my update on v7.0.1, but i think the difference between v7.0.1 & v8 is minor, so we can catch up with v8 easily.

**Comment by XVilka** [comment]
@blacktop I think it is the master that failing too: https://travis-ci.org/aquynh/capstone/builds/492291404?utm_source=github_status

**Comment by XVilka** [comment]
And errors is missing instruction:
```
arch/AArch64/AArch64InstPrinter.c:479:16: error: use of undeclared identifier
      'ARM64_INS_IC'
                                        insn_id = ARM64_INS_IC;
                                                  ^
arch/AArch64/AArch64InstPrinter.c:486:16: error: use of undeclared identifier
      'ARM64_INS_IC'
                                        insn_id = ARM64_INS_IC;
                                                  ^
arch/AArch64/AArch64InstPrinter.c:490:16: error: use of undeclared identifier
      'ARM64_INS_IC'
                                        insn_id = ARM64_INS_IC;
                                                  ^
arch/AArch64/AArch64InstPrinter.c:499:16: error: use of undeclared identifier
      'ARM64_INS_DC'
                                        insn_id = ARM64_INS_DC;
                                                  ^
arch/AArch64/AArch64InstPrinter.c:506:16: error: use of undeclared identifier
      'ARM64_INS_DC'
                                        insn_id = ARM64_INS_DC;
                                                  ^
arch/AArch64/AArch64InstPrinter.c:511:16: error: use of undeclared identifier
      'ARM64_INS_DC'
                                        insn_id = ARM64_INS_DC;
```

**Comment by aquynh** [comment]
> @blacktop I think it is the master that failing too: https://travis-ci.org/aquynh/capstone/builds/492291404?utm_source=github_status

fixed now

**Comment by blacktop** [comment]
@aquynh I see there have been many changes even to AARCH64.  Do you have time today to help me get this PR ready?

**Comment by blacktop** [comment]
The changes to AARCH are you using the "patches" or are they no longer needed as I remember you saying earlier that you were going to get in sync with 7.0 so the patches wouldn't be needed anymore?

**Comment by aquynh** [comment]
i dont remember we had any important change on Arm64 recently, if any.

i am not sure about the "patches" you are mentioning. do you mean the tablegen patch? if so, then no i dont use that, but wrote some scripts myself, that i believe is much easier to maintain, and work for all arches.

i am working on Arm update right now, then will move to Arm64 later. will look at this PR then (sorry i have very little time now).

**Comment by blacktop** [comment]
@aquynh can you please point me to the scripts you use that are much easier than the tablegen patches please?

**Comment by aquynh** [comment]
WIP. I will publish when those are ready.

**Comment by blacktop** [comment]
Awesome! I'll keep an eye out for it.

**Comment by aquynh** [comment]
now i start working on Arm64 update. do you mind splitting this PR into another one, which only includes changes on **.c** & **.h** files, and make a new pull req for branch https://github.com/aquynh/capstone/tree/next-arm64?

thanks!

**Comment by blacktop** [comment]
@aquynh done

**Comment by XVilka** [comment]
Should be this one closed then?

**Comment by aquynh** [comment]
supported now in the next branch, thanks.

**Pull request closed without merging**
