### PR TITLE
maintain LD_LIBRARY_PATH variable

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by aquynh** [comment]
cool, but this still fails on MacOS?

**Comment by stephengroat** [comment]
sorry, this is me trying to mentally work through issues. i just made a pr marker to remember to work on it

**Comment by stephengroat** [comment]
Sorry about the time, just figured this out. an issue with the `for` loop creating a sub shell, should be fixed by this commit

**Comment by aquynh** [comment]
merged, thanks!

yes, please fix this in "master", too.

**Pull request merged**
