### PR TITLE
cleanup travis and use environment variables

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
i cherry-picked this to the "next" branch, and now Linux build breaks. would you mind taking a look?

https://travis-ci.org/aquynh/capstone/jobs/284714039

**Comment by stephengroat** [comment]
@aquynh is `make` or `cmake` the best build system for the `next` branch?

**Comment by aquynh** [comment]
i guess most *nix users just use "make", but Windows build is better with "cmake".

**Comment by aquynh** [comment]
i temporarily reverted this commit in the "next" branch for now.

**Pull request merged**
