### PR TITLE
Use whole corpus for regression testing

### PR DESCRIPTION
**Pull request by catenacyber**
As recommended by @kcc in
https://github.com/google/oss-fuzz/issues/1989#issuecomment-443368973
The longest part for this addition is the unzipping

I am unsure about where to put the corpus :
- I chose on my web site, but it is not guaranteed to last forever
- on GitHub with the source code, but it will overload the versioning (155M of binary files)
- from Google Cloud, but travis will have to authenticate itself...

Last note : I wrote a new driver for the fuzz harness which fuzzes all the files in a directory passed as the only argument

### CODE REVIEW

**Comment by aquynh** [comment]
how about creating another repo, like CapstoneFuzz, to keep the binary?

**Comment by radare** [comment]
imho the whole fuzzing thing and testsuite should be in separate repositories

**Comment by catenacyber** [comment]
> how about creating another repo, like CapstoneFuzz, to keep the binary?

Sounds a better idea than the ones I had

Will Capstone's Travis be able to access this new repo ? with some `git clone` command in the prescript phase

**Comment by aquynh** [comment]
On Fri, Dec 7, 2018, 02:22 Catena cyber <notifications@github.com wrote:

> how about creating another repo, like CapstoneFuzz, to keep the binary?
>
> Sounds a better idea than the ones I had
>
> Will Capstone's Travis be able to access this new repo ? with some git
> clone command in the prescript phase
>
Yes it can, because new repo is public. We need to update Travis setup then.

Let me open a new repo, then you can do pull req there.

**Comment by aquynh** [comment]
On Thu, Dec 6, 2018, 22:57 radare <notifications@github.com wrote:

> imho the whole fuzzing thing and testsuite should be in separate
> repositories.
>

I have no object for this.

>

**Comment by aquynh** [comment]
@catenacyber, could you please make pull req for fuzzing data on this repo?

https://github.com/groundx/capstonefuzz

**Comment by catenacyber** [comment]
@aquynh ok, I pushed the zip file on the other repo, and modified travis.yml in this pull request accordingly

**Comment by catenacyber** [comment]
Travis check is failing until https://github.com/groundx/capstonefuzz/pull/1 is merged

**Comment by aquynh** [comment]
merged that.

now we can consider either leaving fuzz code here, or move it to the other repo. i am fine with both ways. @catenacyber, what do you prefer?

**Comment by catenacyber** [comment]
I am not sure what is best.
I guess that fuzz code (as other test code) do not bother much simple capstone users (as a 50 Mb binary file with test inputs would have when you clone the repository)

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
