### PR TITLE
fix compiling error in MS VS2015

### PR DESCRIPTION
**Pull request by noword**
for issue #868

### CODE REVIEW

**Comment by aquynh** [comment]
do you have any input affected by this issue?

**Comment by noword** [comment]
I run the test_arm.py.
It looks fine.

**Comment by aquynh** [comment]
no, i mean: does this really fixes some bugs? if it does, can you provide an input?

**Comment by noword** [comment]
It's not a bug.
This code works fine in GCC, but doesn't in MSVC 2015.
Maybe the compiler of MSVC consider that this code is illegal for C grammar.

**Comment by aquynh** [comment]
can you post the warning produced by MSVC here?

**Comment by noword** [comment]
1>....\arch\ARM\ARMInstPrinter.c(1162): error C4146: unary minus operator applied to unsigned type, result still unsigned

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
