### PR TITLE
Use Intel register syntax for Tricore

### PR DESCRIPTION
**Pull request by XVilka**
Addresing this issue: https://github.com/TriDis/ditricore/issues/1#issuecomment-1605066729

### CODE REVIEW

**Comment by XVilka** [comment]
@imbillow @arkup take a look please

**Review by b1llow — APPROVED** [review]

**Comment by arkup** [comment]
@XVilka looks good thanks. I will do more test during the weekend after the merge

**Comment by b1llow** [comment]
> @imbillow @arkup take a look please

One question: Do intermediate values need to be prefixed with #?

**Comment by arkup** [comment]
> > @imbillow @arkup take a look please
> 
> One question: Do intermediate values need to be prefixed with #?

Well, it would be great if 0x... were prefixed with #0x..., as it's Tricore listing / formatting used in the IDA/Ghidra/Lauterbach debugger. If someone is parsing an ASM listing from another tool, it would make things a bit easier to have the same formatting.

**Comment by kabeor** [comment]
Thanks, merged.

**Comment by arkup** [comment]
sorry, it seems that something went wrong. I just compiled it in my own application, and now the some mnemonics are messed up.

previously:

```
.text:8000041c mov.aa %a14, %sp
.text:8000041e sub.a %sp, 0x20
.text:80000420 st.w [%a14]-0xc, %d4
.text:80000424 st.w [%a14]-0x10, %d5
.text:80000428 st.w [%a14]-0x14, %d6
.text:8000042c st.w [%a14]-0x18, %d7
.text:80000430 mov %d15, 0xa
.text:80000432 st.w [%sp]0, %d15
.text:80000434 mov %d15, 0xb
.text:80000436 st.w [%sp]1, %d15
```

now:

```
.text:8000041c a14, sp
.text:8000041e oq31 0x20
.text:80000420 x [a14]-0xc, d4
.text:80000424 x [a14]-0x10, d5
.text:80000428 x [a14]-0x14, d6
.text:8000042c x [a14]-0x18, d7
.text:80000430 jz d15, 0xa
.text:80000432 h.b0, d15
.text:80000434 jz d15, 0xb
.text:80000436 h.b1, d15
```
@XVilka could you please have a look?

**Comment by XVilka** [comment]
@arkup strange; my changes shouldn't affect that. Could you try please without this commit? https://github.com/capstone-engine/capstone/commit/3341c1a171494071ce12c75fca9a85135a616b96

**Comment by arkup** [comment]
@XVilka I did quick test and without this commit I get the same problem. I mean mnemonics are messed up but I will double check in the evening.

**Comment by XVilka** [comment]
Sorry, I forgot to regenerate the files, lol. @imbillow since you want to change the immediate format to use `#`, could you please update autogenerated files too?

**Comment by b1llow** [comment]
> Sorry, I forgot to regenerate the files, lol. @imbillow since you want to change the immediate format to use `#`, could you please update autogenerated files too?

Okay, I should be able to finish this today.

**Pull request merged**
