### PR TITLE
Python2 leftovers v2

### PR DESCRIPTION
**Pull request by twizmwazin**
**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every API function and struct this PR changes.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Rebases #2378 onto `next`, adds a commit updating shebangs to python3, I only found one.

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by Rot127 — APPROVED** [review]
Please delete `test_corpus.py`. Shouldn't be used anywhere now.

**Comment by twizmwazin** [comment]
I also noticed that there are some files in `suite` that are unported. Do we need to port those?

**Comment by XVilka** [comment]
Most of the `suite` files probably should be removed as they are deprecated in favor of [auto-sync](https://github.com/capstone-engine/capstone/issues/2015) tools.

**Review by Rot127 — APPROVED** [review]
@kabeor @aquynh Please take a look.

**Comment by Rot127** [comment]
> Most of the suite files probably should be removed as they are deprecated in favor of https://github.com/capstone-engine/capstone/issues/2015 tools.

Yes, but let's do this before `v6` (not here). Because they are not used. But this code here is run in the CI. Cleaning up `suite` is more than just the Pythin 2 files.

**Comment by Rot127** [comment]
@twizmwazin Any chance you find time to finish https://github.com/capstone-engine/capstone/pull/2369 on behalf of @pyrox0? It is the only one for `v5.0.2`

**Review by kabeor — APPROVED** [review]
Thanks, merged!

**Pull request merged**
