### PR TITLE
Add register access info for ARM64

### PR DESCRIPTION
**Pull request by pranith**
This change adds register access information to ARM64 architecture. Most of it was done looking at how it was implemented for ARM. Tested slightly(the inst_ops[] was not modified except for fixing the sizes). Please pull!

### CODE REVIEW

**Comment by pranith** [comment]
I can now see some indentation issue. Also I think I use get_op_access() too many times. Let me know if you want me to correct and resend another pull request or to work on top of this.

**Comment by aquynh** [comment]
excellent, this is a good start! the info is there for awhile, but i have no time to integrate that yet. thanks for stepping up to finish this work.

can you separate all the operand access info into a separate file AArch64MappingInsnOp.inc, like what we are doing with ARMMappingInsnOp.inc?

i will take a closer look soon, thanks!

**Comment by pranith** [comment]
I will separate them into the new file. Please let me know what other comments you have. I will create a new pull request.

**Comment by pranith** [comment]
@aquynh I updated this pull request by separating the info into a separate file. 

Please let me know how it looks.

**Comment by aquynh** [comment]
sorry for taking too much time on this PR! i will look at it this wekend, thanks.

**Comment by bughoho** [comment]
good job!

**Comment by aquynh** [comment]
this pull request accidentally added file `arch/AArch64/ARMMappingInsnOp.inc`, which is conventionally named for ARM arch, not AArch64?

thanks

**Comment by pranith** [comment]
Sorry, that was a mistake while adding the AArch64 mappings. I've updated the pull request.

**Comment by aquynh** [comment]
nice work! i did some minor fixes on compilation warnings & indentation, then push this to a new branch "arm64" at https://github.com/aquynh/capstone/tree/arm64. please base your next PR on this branch. i will merge this back to the "next" branch when it is ready.

i run `tests/test_arm64`, and have some output like below:

```
0x38:	tbx	v0.8b, {v1.16b, v2.16b, v3.16b}, v2.8b
	op_count: 5
		operands[0].type: REG = v0
		operands[0].access: READ | WRITE
			Vector Arrangement Specifier: 0x1
		operands[1].type: REG = v1
		operands[1].access: READ
			Vector Arrangement Specifier: 0x2
		operands[2].type: REG = v2
		operands[2].access: READ
			Vector Arrangement Specifier: 0x2
		operands[3].type: REG = v3
			Vector Arrangement Specifier: 0x2
		operands[4].type: REG = v2
			Vector Arrangement Specifier: 0x1
	Registers read: v0 v1 v2
	Registers modified: v0
```

we have v0, v1, v2 are read. so we are missing **v3** here, right?

thanks

**Comment by aquynh** [comment]
Pranith, can you please confirm?

**Comment by pranith** [comment]
@aquynh I tried looking into it. Not sure where the bug is though. We need to iterate over the vector register list in the instruction operand, this info is sadly not correct. You can observe that even the access permission for v3 is missing.

**Comment by aquynh** [comment]
i fixed this issue with this commit: https://github.com/aquynh/capstone/commit/4b5dc21fa95a1273860e671875559497bfab683f

**Comment by aquynh** [comment]
i merged this to the "next" branch, and credited your work with the commit https://github.com/aquynh/capstone/commit/1c22c2645cfc8c45f2b483844d8d7ec62803ab40. thanks!

**Comment by pranith** [comment]
@aquynh thanks a ton for fixing it.

**Comment by aquynh** [comment]
the table of access registers still needs more love, for example like this commit https://github.com/aquynh/capstone/commit/885e488a2e01b4576fe7df97ed17aa2326ca6e9f. if you find incorrect info like this, please help to fix it.

thanks.

**Pull request merged**
