### PR TITLE
Fix memory leak in RISC V

### PR DESCRIPTION
**Pull request by catenacyber**
Found by oss-fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13686

### CODE REVIEW

**Comment by aquynh** [comment]
@fanfuqiang, please ack.

**Comment by aquynh** [comment]
@fanfuqiang i just merge this simple fix.

thanks!

**Comment by fanfuqiang** [comment]
Sorry missing the message, I am busy at another project.
The patch of @catenacyber is correct, I think.

**Comment by aquynh** [comment]
Can you update the tablegen patch?

**Comment by fanfuqiang** [comment]
> Can you update the tablegen patch?
3 minutes.

**Pull request merged**
