### PR TITLE
Make install.sh more idomatic

### PR DESCRIPTION
**Pull request by tmfink**
Use parameter expansion modifiers instead of manual tests.

Tested on Ubuntu 18.04 and FreeBSD 11

### CODE REVIEW

**Comment by aquynh** [comment]
nice work! looks like this can still work on older shells?

**Comment by tmfink** [comment]
> nice work! looks like this can still work on older shells?

Thanks! Yes, parameter expansion should work for any `/bin/sh` compatible shell in the last 30(?) years.

**Comment by aquynh** [comment]
why do you change $* to $@?

**Comment by tmfink** [comment]
> why do you change $* to $@?

`$*` expands to a single string; when not quoted, spaces act as separators.

`"$@"` is special and preserves arguments (shifts get rid of early arguments). For example, you could do:

~~~
./make.sh default "CFLAGS=-flag1 -flag2" "CC=mycompiler"
~~~

which will preserve `CFLAGS` with spaces.

https://linux.die.net/man/1/ash

**Comment by radare** [comment]
Making shellscript more idiomatic grinches me a bit. This pr is reintroducing bashisms that are basically making it less portable

**Comment by radare** [comment]
nvm misread, lgtm

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
