### PR TITLE
Fix Thumb disassembler memory corruption with IT sequence (issue #385)

### PR DESCRIPTION
**Pull request by igotti-google**

### CODE REVIEW

**Comment by aquynh** [comment]
currently the limit of `ITStates` is fixed at 128, so this can be overflowed when we have more than 128 IT instructions in a row.

any idea on how to properly solve this problem?

**Comment by igotti-google** [comment]
Nested IT is disallowed by ARM, so it's invalid instruction sequence. We may just return an error.
Overflow prevention code is in the pull request.

**Comment by aquynh** [comment]
yes, but because you return immediately when seeing the nested IT instruction, i dont see why the overflow check is necessary.

**Comment by igotti-google** [comment]
This function may be called from other places in the future, so it's just to prevent such bugs in the future I fixed both callee and caller.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by igotti-google** [comment]
Thanks! Could you please merge that to 'next' as well?

**Comment by aquynh** [comment]
yes, i just did it, thanks!

**Comment by aquynh** [comment]
at the same time, i reduced the array size of `ITStates[]` to 8: https://github.com/aquynh/capstone/commit/8bd0fdb992c54895a17965bd602d90999a023dfc

thanks.

**Pull request merged**
