### PR TITLE
cstest: use DOWNLOAD_EXTRACT_TIMESTAMP conditionally

### PR DESCRIPTION
**Pull request by hainest**
**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every API function and struct this PR changes.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)

N/A

**Detailed description**
This feature was added in CMake 3.24.0, so this allows older CMakes to still build the tests.

**Test plan**
N/A

**Closing issues**
N/A

### CODE REVIEW

**Comment by Rot127** [comment]
```
 Enabling CAPSTONE_XTENSA_SUPPORT
CMake Error at /usr/local/share/cmake-3.31/Modules/ExternalProject/shared_internal_commands.cmake:1091 (message):
  URL_HASH is set to

    SHA256=810570eb0b8d64804331f82b29ff47c790ce9cd6b163e98d47a4807047ecad82;DOWNLOAD_EXTRACT_TIMESTAMP true

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512

  and value is a hex string.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.31/Modules/ExternalProject.cmake:3041 (_ep_add_download_command)
  suite/cstest/CMakeLists.txt:13 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
```

**Comment by hainest** [comment]
Interesting. That's the exact error this fixes. I'm not able to reproduce it.

```console
docker run --rm -it ubuntu:22.04
apt install -y cmake git g++ libyaml-dev

cmake --version
  cmake version 3.22.1

git clone --depth=1 https://github.com/capstone-engine/capstone.git
cd capstone
git fetch origin pull/2581/head:PR2581
git checkout PR2581
mkdir build
cd build
cmake .. -DCAPSTONE_BUILD_SHARED_LIBS=ON -DCAPSTONE_BUILD_CSTEST=ON
```

**Review by Rot127 — APPROVED** [review]
Thanks a lot! Really appreciate it.

**Comment by XVilka** [comment]
@kabeor

**Review by Rot127 — APPROVED** [review]

**Review by kabeor — APPROVED** [review]
Thank you.

**Pull request merged**
