### PR TITLE
Update Python bindings and test them in CI

### PR DESCRIPTION
**Pull request by peace-maker**
There is a test setup for the python bindings in the `bindings/Makefile`, which compare the output of the `/tests/test_<arch>` programs with the equivalent `bindings/python/test_<arch>.py` scripts. They weren't run in CI and the tests were heavily out of sync.

I've fixed all issues with the Python bindings that popped up while fixing the tests. This resulted in new bindings for the wasm and sh targets. 🎉 

I'm aware of the plans to unify the tests using cstest, but figured any tests for the bindings at all are better than nothing in the meantime. The Java bindings are heavily outdated, so I've disabled tests for them until they're taken care of.

### CODE REVIEW

**Comment by XVilka** [comment]
@peace-maker thank you! Despite plans to unify tests, testing bindings separately is also required, so it's not a duplicate work anyway: https://github.com/capstone-engine/capstone/issues/2043

**Comment by XVilka** [comment]
I think it would be a perfect fit for the bug fix release if it happens: https://github.com/capstone-engine/capstone/issues/2081

**Comment by XVilka** [comment]
@kabeor @aquynh

**Comment by aquynh** [comment]
looks nice, but do you mind splitting this PR into a few independent PRs, instead of mixing all of them into one?

**Comment by XVilka** [comment]
Resulting PRs:
- https://github.com/capstone-engine/capstone/pull/2095
- https://github.com/capstone-engine/capstone/pull/2096
- https://github.com/capstone-engine/capstone/pull/2097

Should be imported also to the `v5` branch (except `auto-sync`-related commit, of course), IMHO.

**Comment by peace-maker** [comment]
I'll wait with the testing part until the other PRs are merged since it depends on them.

**Pull request closed without merging**
