### PR TITLE
[ARM] Remove LDM leftover code

### PR DESCRIPTION
**Pull request by Rot127**
Some forgotten leftover code which is already handled with patches or in ARMMapping.c

### CODE REVIEW

**Comment by Rot127** [comment]
Added accidentally two more unrelated fixes to this branch. Let me know if you'd like them in a separated PR.

**Comment by kabeor** [comment]
@Rot127 Hi，needn't to separate this time, but can you describe more about these two commits in this PR's detail widget?

**Comment by Rot127** [comment]
@kabeor I extended the commit description. Its better for future people as well.

**Comment by kabeor** [comment]
ok thanks.

**Pull request merged**
