### PR TITLE
Updated setup.py so it can build the capstone library by itself.

### PR DESCRIPTION
**Pull request by scudette**
This is a requirement for an automated install via pip. After this change it
should be possible to depend on captone in pip and have it built automatically.

### CODE REVIEW

**Comment by scudette** [comment]
I fixed the case where on OSX the library is built with the .so extension (Although it doesnt seem to matter - either extension apparently works). I also ensured that the src/ directory is created if it is not there for the case where one tries to install a checked out github copy.

I tested on OSX and it seems to work now. Please check if there are any more issues.

**Comment by aquynh** [comment]
currently your approach is trying to duplicate this work, and as a result, on my Yosemite OSX the core cannot be compiled due to (it seems) some wrong compiler flags.

i think it is simpler & cleaner to just execute `make.sh` to compile the core: `make.sh` already know all the compiler setup & would take care all all the platforms (OSX, Linux, *BSD, etc) to generate the right library (.dylib or .so).

**Comment by scudette** [comment]
That is strange as I tested on a Yosemite box and it worked fine. The issue
is that the pip package must carry everything it needs with it. Since the C
code is not well contained in its own directory, we need to copy files
carefully into the ./src/ directory in such a way that we could run make.sh
after we package it. It will be a lot of work and also be error prone as we
need to maintain the mapping between the original source tree and the tree
distributed in the sdist. (Maybe a future cleanup of the c code will help
this issue - like creating an isolated /src/ directory at the top level.).

In addition we need to rewrite make.sh as a batch file since windows does
not have bash or indeed make at all for the pip package to be compiled on
windows. This will be even harder to maintain. Setup tools is designed to
build python modules and somewhat designed to build simple C libraries.
Considering how simple the make.sh file is I dont see a point in the added
complexity of trying to incorporate it into the python build process.

Can you please indicate which compiler options are missing on darwin? What
is the difference between the options invoked through the make file and
those through the python bindings?

Thanks
Michael.

**Comment by aquynh** [comment]
sorry i dont really get why your patch copies source to src/: in reality, "pip install" would copy the core from somewhere online, such as http://capstone-engine.org/download/3.0/capstone-3.0.tgz, the unzip and compile (better to do with `make.sh`, no? then there is no more issue of wrongly duplicating the source?

i guess we should not compile on Windows, as it would require C compiler that most people do not have on their machine. so there are 2 choices:

(1) totally ignore compile/install this PyPi for Windows. we already provide the binary installer for Windows in http://capstone-engine.org/download.html, so this should be fine.

(2) we can provide the precompiled core (capstone.dll) with the PyPi package, so no Windows compilation is needed. still we need to figure out how to setup this properly.

thanks.
thanks.

**Comment by scudette** [comment]
When you upload a package to pip you upload essentially the sdist package
that your setup.py produces. I dont think it is expected that when you do a
pip install it will download another package and build it externally (I
might be wrong on this one though).  Note that on windows there is nothing
that will unpack tgz files either.

The main reason I want the pip installer to build the C module is that I
need to have it install automatically on windows. distutils already
supports it so why no do things in a standard way? Providing the
precompiled library for windows is actually problematic (although possible)
I know of a couple of projects who accidentally distribute 64bit dlls for
32 bit windows and this does not work (i.e. they end up having broken pip
installers) (e.g. the unofficial yara binding has this problem).

**Comment by aquynh** [comment]
On Jan 27, 2015 8:25 AM, "Michael Cohen" <notifications@github.com> wrote:
>
> When you upload a package to pip you upload essentially the sdist package
> that your setup.py produces. I dont think it is expected that when you do
a
> pip install it will download another package and build it externally (I
> might be wrong on this one though).

I think that would be fine, as many package solutions are doing exactly
that: brew, macports, all the BSD OS, etc. Not on Windows, but i dont see
how to compile C code on Windows for most people.

i am not against yor approach, but this needs more fixes: currently the
core does not compile because it cannot find ../../utils.h

>
> The main reason I want the pip installer to build the C module is that I
> need to have it install automatically on windows. distutils already
> supports it so why no do things in a standard way?

But most users do not have C compiler on their Windows machine. It is not
reasonable to ask them to have C compiler just to install a PyPi package.

Thanks

>
> On 27 January 2015 at 01:14, Nguyen Anh Quynh <notifications@github.com>
> wrote:
>
> > sorry i dont really get why your patch copies source to src/: in
reality,
> > "pip install" would copy the core from somewhere online, such as
> > http://capstone-engine.org/download/3.0/capstone-3.0.tgz, the unzip and
> > compile (better to do with make.sh, no? then there is no more issue of
> > wrongly duplicating the source?
> >
> > i guess we should not compile on Windows, as it would require C
compiler
> > that most people do not have on their machine. so there are 2 choices:
> >
> > (1) totally ignore compile/install this PyPi for Windows. we already
> > provide the binary installer for Windows in
> > http://capstone-engine.org/download.html, so this should be fine.
> >
> > (2) we can provide the precompiled core (capstone.dll) with the PyPi
> > package, so no Windows compilation is needed. still we need to figure
out

**Comment by aquynh** [comment]
post again because Github messed up my answer.
>
> When you upload a package to pip you upload essentially the sdist package 
> that your setup.py produces. I dont think it is expected that when you do a 
> pip install it will download another package and build it externally (I 
> might be wrong on this one though).

I think that would be fine, as many package solutions are doing exactly that: brew, macports, all the BSD OS, etc. Not on Windows, because  i dont see how to compile on Windows for most people.

i am not against yor approach, but this needs more fixes: currently the core does not compile because it cannot find ../../utils.h

>
> The main reason I want the pip installer to build the C module is that I 
> need to have it install automatically on windows. distutils already 
> supports it so why no do things in a standard way?

But most users do not have C compiler on their Windows machine. It is not reasonable to ask them to have C compiler just to install a PyPi package.

Thanks

**Comment by aquynh** [comment]
on OSX 10.10, i got following errors for `cd bindings/python; sudo make install` (no such error if i compiled the core with `.make.sh` from the root directory)


cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./src/include/ -c ./src/cs.c -o ./build/temp.macosx-10.10-intel-2.7/./src/cs.o -D CAPSTONE_X86_ATT_DISABLE_NO -D CAPSTONE_DIET_NO -D CAPSTONE_X86_REDUCE_NO -D CAPSTONE_HAS_ARM -D CAPSTONE_HAS_ARM64 -D CAPSTONE_HAS_MIPS -D CAPSTONE_HAS_POWERPC -D CAPSTONE_HAS_SPARC -D CAPSTONE_HAS_SYSZ -D CAPSTONE_HAS_X86 -D CAPSTONE_HAS_XCORE -D CAPSTONE_USE_SYS_DYN_MEM -D CAPSTONE_SHARED -arch i386 -arch x86_64 -O2 -Wall -fPIC
./src/cs.c:366:21: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'cs_opt_value' (aka 'enum cs_opt_value') [-Wshorten-64-to-32]
                        handle->detail = value;
                                       ~ ^~~~~
.....
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -pipe -I./src/include/ -c ./src/arch/AArch64/back/AArch64BaseInfo.c -o ./build/temp.macosx-10.10-intel-2.7/./src/arch/AArch64/back/AArch64BaseInfo.o -D CAPSTONE_X86_ATT_DISABLE_NO -D CAPSTONE_DIET_NO -D CAPSTONE_X86_REDUCE_NO -D CAPSTONE_HAS_ARM -D CAPSTONE_HAS_ARM64 -D CAPSTONE_HAS_MIPS -D CAPSTONE_HAS_POWERPC -D CAPSTONE_HAS_SPARC -D CAPSTONE_HAS_SYSZ -D CAPSTONE_HAS_X86 -D CAPSTONE_HAS_XCORE -D CAPSTONE_USE_SYS_DYN_MEM -D CAPSTONE_SHARED -arch i386 -arch x86_64 -O2 -Wall -fPIC
./src/arch/AArch64/back/AArch64BaseInfo.c:23:10: fatal error: '../../utils.h' file not found
#include "../../utils.h"
         ^
1 error generated.
error: command 'cc' failed with exit status 1

**Comment by scudette** [comment]
On 27 January 2015 at 01:41, Nguyen Anh Quynh <notifications@github.com>
wrote:

> I think that would be fine, as many package solutions are doing exactly
> that: brew, macports, all the BSD OS, etc. Not on Windows, but i dont see
> how to compile C code on Windows for most people.
>

Compiling code on windows is a pretty standard thing - install msvc, run
setup.py install. Not more difficult than say OSX which also does not come
with compilers installed.


> i am not against yor approach, but this needs more fixes: currently the
> core does not compile because it cannot find ../../utils.h


As I mentioned this is because the original source code is not well
contained and we need to copy files very carefully into the src directory.
I think the use of ../.. in #include statements is not considered good
practice for this reason (There are many lines like:

./bindings/python/src/arch/XCore/XCoreInstPrinter.c:#include "../../utils.h"

Which fail because the files are reodered. If I might suggest this is a
problem in the c code. You should just add required include paths via the
-I switch and simply

#include "utils.h"

Ideally the c code would all live inside a toplevel directory called "src"
instead of being spread out throughout the tree.

Anyway I am not seeing this issue. I am running python setup.py build from
within the bindings/python directory - so the include just works for me. My
directory structure looks like this:

~/projects/capstone/bindings/python$ ls src/
arch               COMPILE.TXT  cs.c          HACK.TXT    LEB128.h
 Makefile          MCFixedLenDisassembler.h  MCInstrDesc.c
MCRegisterInfo.h  README         SStream.h
COMPILE_CMAKE.TXT  config.mk    cs_priv.h     include     LICENSE_LLVM.TXT
 MathExtras.h      MCInst.c                  MCInstrDesc.h     msvc
     RELEASE_NOTES  utils.c
COMPILE_MSVC.TXT   CREDITS.TXT  functions.mk  inttypes.h  LICENSE.TXT
MCDisassembler.h  MCInst.h                  MCRegisterInfo.c  pkgconfig.mk
     SStream.c      utils.h

Can you please delete the bindings/python/src/ directory to ensure the
setup.py creates a proper one?


>
> >
> > The main reason I want the pip installer to build the C module is that I
> > need to have it install automatically on windows. distutils already
> > supports it so why no do things in a standard way?
>
> But most users do not have C compiler on their Windows machine. It is not
> reasonable to ask them to have C compiler just to install a PyPi package.
>

Many pypi packages need to build their c modules. It is not unusual and is
the normal way to install binary c modules (that you need to compile). If
one does not have a compiler they need to download and install the msi
packages separately (i.e. not through pypi). The strength of pypi is that
it will fetch and install all dependencies for you automatically and
therefore it is less manually intensive than downloading individual
packages.

Thanks
Michael.

**Comment by aquynh** [comment]
on OSX, i deleted src/, then compiled again, but still get the same error.
please see the output at https://gist.github.com/aquynh/8b16e333ade1ba1029c9

thanks.

**Comment by aquynh** [comment]
i still think a good solution is to use `make.sh` to compile the core, so the generated libraries use the same consistent compile setup everywhere.

thanks.

**Comment by aquynh** [comment]
on putting all the C code under src/, if you send a pull request to do that, i would merge.

thanks.

**Comment by tacoxnguyen** [comment]
@scudette I have just merge base repo with your repo. I tested your setup script on Mac OS X and I must edit some code to make it work. You can check out my commit at https://github.com/tacoxnguyen/capstone/commit/ead10b7a60a5bced1828bb52cf3830518dbe0d52.

thanks.

**Comment by scudette** [comment]
Ah thanks for fixing. I typoed this when I figured out how to change the
name of the built extension. By default it makes it a .so which actually
works fine (at least for python) but it was required to be .dylib on osx
for consistency.
Am 27.01.2015 05:41 schrieb "tacoxnguyen" <notifications@github.com>:

**Comment by aquynh** [comment]
fyi, i fixed some issues on my machine, and now i can compile the latest code from @tacoxnguyen.

**Comment by aquynh** [comment]
i close this because the code is already merged into the `pypi` branch.

thanks.

**Pull request closed without merging**
