### PR TITLE
Fix spelling nits

### PR DESCRIPTION
**Pull request by ttsugriy**
I was playing with this awesome disassembly engine and while reading the awesome code documentation, I made a few minor spelling fixes along the way and since I follow the Boy Scout rule, wanted to contribute them back.

Thank you for this engine!

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by ttsugriy** [comment]
Thank you! Your documentation rocks! Way to go!

On Tue, May 5, 2015 at 3:03 PM, Nguyen Anh Quynh <notifications@github.com>
wrote:

> merged, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aquynh/capstone/pull/354#issuecomment-99235723>.
>



-- 
Best regards,
Taras Tsugrii

**Comment by aquynh** [comment]
also merged this into the "next" branch.

the "next" branch is where we put all the development effort for v4.0, and there are quite a lot of changes in `capstone.h` compared to the "master" branch. if you see any spelling issues there, please fix them too.

https://github.com/aquynh/capstone/blob/next/include/capstone/capstone.h

thanks.

**Comment by ttsugriy** [comment]
I'll definitely do that! Hopefully at some point I'll be able to contribute
something more interesting than spelling fixes, but you don't leave too
much room for improvement :)

On Tue, May 5, 2015 at 3:09 PM, Nguyen Anh Quynh <notifications@github.com>
wrote:

> also merged this into the "next" branch.
>
> the "next" branch is where we put all the development effort for v4.0, and
> there are quite a lot of changes in capstone.h compared to the "master"
> branch. if you see any spelling issues there, please fix them too.
>
> https://github.com/aquynh/capstone/blob/next/include/capstone/capstone.h
>
> thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aquynh/capstone/pull/354#issuecomment-99242546>.
>



-- 
Best regards,
Taras Tsugrii

**Pull request merged**
