### PR TITLE
+vb6 bindings

### PR DESCRIPTION
**Pull request by dzzie**

### CODE REVIEW

**Comment by aquynh** [comment]
wow, another fantastic work from you! what is the current status of this binding?

**Comment by dzzie** [comment]
hi, all of the capstone api are implemented except cs_disasm_iter. It can disassemble any of the arch supported by capstone,  however full instruction details are currently only implemented for the x86 processor family. sample was built against the binary release of Capstone 3.0 rc4. a screen shot is included in the repo

https://github.com/dzzie/capstone/blob/fb9af8d2baf140c912d1aa56efbb32a31cc4ff35/bindings/vb6/screenshot.png

**Comment by aquynh** [comment]
merged, thanks!

can you please add your name to https://github.com/aquynh/capstone/blob/next/CREDITS.TXT?

**Comment by dzzie** [comment]
ok added thanks

**Pull request merged**
