### PR TITLE
improve type safety, use ppc_reg instead of unsigned int

### PR DESCRIPTION
**Pull request by kevemueller**
use the available ppc_reg typedef instead of the generic unsigned int

### CODE REVIEW

**Comment by aquynh** [comment]
given that you want to change only 1 line in file include/ppc.h, it is a real mess. did you happen to edit this file on Windows? would you mind fixing this?

thanks.

**Comment by kevemueller** [comment]
I had to move the block below the definition of ppc_reg. That's all. No line ending or similar changes made.

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
would you do this for the "next" branch, too?

**Pull request merged**
