### PR TITLE
Add travis test framework

### PR DESCRIPTION
**Pull request by pranith**
This PR adds travis test framework to build and run the tests using travis-ci.org. These will basically look like this once enabled: https://travis-ci.org/pranith/capstone/jobs/112769826

### CODE REVIEW

**Comment by aquynh** [comment]
merged, thanks!

**Comment by aquynh** [comment]
now README uses markdown, feel free to change the references there (like COMPILE.TXT, HACK.TXT, etc) to links :-)

**Comment by pranith** [comment]
You're welcome. Please note that the tests fail currently. To fix that, we need to:

* install the library properly for tests
* Exit should return 1 to indicate test failure. I'll try to work on them

**Comment by aquynh** [comment]
great, look forward to more PRs on these issues!

**Comment by aquynh** [comment]
can you also add Travis support for Python binding? we can run "make check" under `bindings/python/` for Python testing.

thanks.

**Pull request merged**
