### PR TITLE
Relocatable package v5

### PR DESCRIPTION
**Pull request by mrexodia**
As per #2431

### CODE REVIEW

**Comment by Rot127** [comment]
Let's wait until we merged something into v5 (like https://github.com/capstone-engine/capstone/pull/2443), rebase this one and get the CI results again.

Just wouldn't want to merge CMake edits without the CI running before.

**Comment by mrexodia** [comment]
I triggered the CI (`git commit --amend`, `git push --force`)

**Review by Rot127 — APPROVED** [review]
Ah yes. This is indeed the smart way :)

**Review by kabeor — APPROVED** [review]
Cool, thanks.

**Pull request merged**
