### PR TITLE
Update PowerShell bindings

### PR DESCRIPTION
**Pull request by beatcracker**
#### Features

* Increased performance. Up to 60x speedup on complex code.
* Native PowerShell [formatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml) for objects.
* General code cleanup and fixes.

####  Breaking changes

* Requires PowerShell 3.0

#### Additions

* `Get-CapstoneVersion` function, returns [version](https://docs.microsoft.com/en-us/dotnet/api/system.version) object.

### CODE REVIEW

**Comment by beatcracker** [comment]
Here are my benchmark results, where I disassemble [Quantum Break](https://pcgamingwiki.com/wiki/Quantum_Break)'s `renderer_x64_f.dll`.

```none
PowerShell version : Desktop | v5.1.14409.1012
Module version     : 0.0.0.2
File name          : renderer_x64_f.dll
Code size          : 3.03 MB
Detailed output    : False


Duration : 00:00:16.9492140
--------------------------------------------------
PowerShell version : Desktop | v5.1.14409.1012
Module version     : 0.0.0.1
File name          : renderer_x64_f.dll
Code size          : 3.03 MB
Detailed output    : False


Duration : 00:18:54.9448597
--------------------------------------------------
```

As you can see, module in this PR it takes 17 seconds to disasemble `.text` section, while original needs almost 19 minutes.

**Comment by aquynh** [comment]
@FuzzySecurity, please can you ack?

**Comment by FuzzySecurity** [comment]
I feel fine with most of the changes, my problem is breaking backwards compat with PSv2. That means it can no longer be used on Win7. I would strongly prefer that compat is restored.

**Comment by beatcracker** [comment]
@FuzzySecurity Me too, but most of the performance benefits come from removing `New-Object` calls and casting to `[pscustomobject]` is not supported in PSv2. But I'll see what I can do.

In the worst case, can we have 2 module versions (PSv2/PSv3+)? I'm willing to backport changes that are PSv2 compatible.

**Comment by beatcracker** [comment]
I've restored `PSv2` compatibilty, `[pscustomobject]`/`New-Object` is now used according to PS version determined in runtime. In any case, we don't need `Select-Object` anymore, which provides substantial speed increase for `PSv2` codepath.

```none
PowerShell version : Desktop | v5.1.14409.1012
Module version     : 0.0.0.2
File name          : renderer_x64_f.dll
Code size          : 3.03 MB
Detailed output    : False


Duration : 00:00:05.2723272
--------------------------------------------------
PowerShell version : Legacy | v2.0
Module version     : 0.0.0.2
File name          : renderer_x64_f.dll
Code size          : 3.03 MB
Detailed output    : False

Duration : 00:00:27.7519900
--------------------------------------------------
```

**Comment by FuzzySecurity** [comment]
@beatcracker looking good, sorry for the delayed reply. I think having backward compat and benefits for people on v3+ is the best solution. Please make sure to add your name to the help file!

@aquynh I think after @beatcracker adds his name to the module help file this should be good to go.

**Comment by beatcracker** [comment]
> Please make sure to add your name to the help file!

This is the best I could do. :shipit:

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
