### PR TITLE
Increment API version to 6

### PR DESCRIPTION
**Pull request by Rot127**

### CODE REVIEW

**Comment by XVilka** [comment]
Requires changes in a few more places:
```
error: [Errno 2] No such file or directory: 'libcapstone.so.5'
```

**Review by XVilka — APPROVED** [review]

**Comment by kabeor** [comment]
Wait, why jump to 6 now?

**Comment by Rot127** [comment]
At least we (and I suspect other projects as well) support multiple CS versions. But the differences between v4, v5 and the next branch are large.
For example: in v5 numerous instructions alias were added as instructions to the `ppc_insn` enum (although they shouldn't because they are alias, not instructions).

With the version 6 in the next branch one can do things like:
```
#if CS_API_MAJOR == 5
...
#endif
#if CS_API_MAJOR == 6
...
#endif
```

**Comment by kabeor** [comment]
However a major version upgrade is a very big jump. Should not be used lightly. I mean eventually we can use 5/6 to distangish different situation, but not now.

**Comment by XVilka** [comment]
@kabeor with ARM merged it's already different. If you want publish `5.x` or `5.0.x` releases there is already `v5` branch to do that.

**Comment by Rot127** [comment]
Superseded by https://github.com/capstone-engine/capstone/pull/2123

**Pull request closed without merging**
