### PR TITLE
Make travis print the fuzzed input to be used with cstool

### PR DESCRIPTION
**Pull request by catenacyber**
Adds architectures and modes to cstool as well

### CODE REVIEW

**Comment by aquynh** [comment]
to test this, perhaps it is better to make pull req to the "next-x86" branch instead, which cannot pass the fuzzer right now, so we can see the result immediately ;-)

**Comment by aquynh** [comment]
could you create a separate PR for the cstool update, so i can merge that to other branches?

**Comment by aquynh** [comment]
i cherry-picked the 1st commit for the next-x86 branch for now, thanks.

**Comment by aquynh** [comment]
already cherry-picked into next, thanks!

**Comment by catenacyber** [comment]
Thanks

There remain 2 modes that are not used in cstool.c : `CS_MODE_QPX` `CS_MODE_MIPS2`
Should they be used ?

**Comment by aquynh** [comment]
I think you can hold on that. Later when i have a major update for Mips,
these modes can even go away, i am not really sure yet.

**Pull request closed without merging**
