### PR TITLE
Fixup.20160411

### PR DESCRIPTION
**Pull request by nplanel**
[python][contrib][objdump] fixup op.register_bits access
[M68K] typo on m68k_address_mode private struct

### CODE REVIEW

**Comment by nplanel** [comment]
Could you add a test on your CI, like "python contrib/objdump/objdump-m68k.py test.m68k.bin" ?

**Comment by aquynh** [comment]
@emoon, can you please confirm this PR?

**Comment by emoon** [comment]
Looks good to me!

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
